//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_UserWorkingTimes
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> OrganizeID { get; set; }
        public string OrganizeName { get; set; }
        public string WorkingTimesID { get; set; }
        public string WorkingTimesName { get; set; }
        public string ParentWorkingTimesID { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public string WorkingType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TimeScope { get; set; }
        public string EndTimeScope { get; set; }
        public Nullable<decimal> WorkHour { get; set; }
        public Nullable<decimal> RestHour { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<int> CardNum { get; set; }
        public Nullable<int> IsPunch { get; set; }
        public Nullable<int> IsPunch2 { get; set; }
        public Nullable<decimal> KnotRestHour { get; set; }
        public Nullable<decimal> LateOverTime { get; set; }
        public Nullable<decimal> LeaveOverTime { get; set; }
        public Nullable<decimal> LateOverTime2 { get; set; }
        public Nullable<decimal> LeaveOverTime2 { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<System.DateTime> TimeScope1 { get; set; }
        public Nullable<System.DateTime> TimeScope2 { get; set; }
        public Nullable<System.DateTime> EndTimeScope1 { get; set; }
        public Nullable<System.DateTime> EndTimeScope2 { get; set; }
    }
}
