//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_OrganizeUserWorkingTimesDetail
    {
        public long UserWorkingTimesID { get; set; }
        public string OrganizeWorkingTimesID { get; set; }
        public string OrganizeID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string ParentID { get; set; }
        public string YearMonth { get; set; }
        public string OrganizeName { get; set; }
    }
}
