//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_SchedulingDetailPre
    {
        public long SchedulingDetail { get; set; }
        public Nullable<long> Scheduling { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<decimal> WorkingQty { get; set; }
        public Nullable<decimal> CleanQty { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string WorkingTimesID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public string AuditAccount { get; set; }
        public string AuditAccountName { get; set; }
        public string NextAccounts { get; set; }
        public string NextAccountNames { get; set; }
        public string AuditAccountLog { get; set; }
        public string AuditAccountNameLog { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
