//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_DayProduction
    {
        public long DayProductionID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<long> DayPlanID { get; set; }
        public Nullable<long> ProcessPlanID { get; set; }
        public Nullable<long> WorkShopID { get; set; }
        public Nullable<long> LineID { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<System.DateTime> StarHour { get; set; }
        public Nullable<System.DateTime> EndHour { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<int> IsTeluk { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<System.DateTime> FeedingDate { get; set; }
        public Nullable<int> TotalPeoples { get; set; }
        public string SSN { get; set; }
    }
}
