//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_OrderMaterialSet
    {
        public long MaterialSetID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string OrderNo { get; set; }
        public string ItemCode { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<decimal> WorkingQty { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> QPA { get; set; }
        public Nullable<decimal> WorkingQtyDemand { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public Nullable<decimal> RcvQty { get; set; }
        public Nullable<decimal> UnIssuedQty { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public Nullable<decimal> OnloadQty { get; set; }
        public Nullable<decimal> OncheckQty { get; set; }
        public Nullable<decimal> MatchingQty { get; set; }
        public Nullable<decimal> MatchingRate { get; set; }
        public string Buyer { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> OweAllQty { get; set; }
        public Nullable<decimal> OnlineQty { get; set; }
    }
}
