//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_DayPlan
    {
        public long DayPlanID { get; set; }
        public Nullable<long> WorkShopID { get; set; }
        public Nullable<long> LineID { get; set; }
        public Nullable<decimal> PlanQty { get; set; }
        public Nullable<decimal> HasQty { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<System.DateTime> FeedingDate { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> ExpectTime { get; set; }
        public Nullable<long> ProcessPlanID { get; set; }
        public Nullable<System.DateTime> PlanDay { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
