//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_SchedulingPre
    {
        public long Scheduling { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string MachineID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<int> CurrentPeoples { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public string Extend6 { get; set; }
        public string Extend7 { get; set; }
        public string Extend8 { get; set; }
        public string Extend9 { get; set; }
        public string Extend10 { get; set; }
        public string Extend11 { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public string Extend17 { get; set; }
        public string Extend18 { get; set; }
        public string Extend19 { get; set; }
        public string Extend20 { get; set; }
        public string Extend21 { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<decimal> GoodQty { get; set; }
        public string MachineMouldID { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<decimal> CheckProgress { get; set; }
        public Nullable<bool> IsAutoScheduling { get; set; }
        public Nullable<int> TotalBoms { get; set; }
        public Nullable<long> WorkShopID { get; set; }
        public Nullable<decimal> UsingHour { get; set; }
        public string YearMonth { get; set; }
    }
}
