//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dev_Menu
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsAllVisible { get; set; }
        public string TargetFor { get; set; }
        public string Url { get; set; }
        public string ParentCode { get; set; }
        public string AppCode { get; set; }
        public string Ico { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public Nullable<bool> IsOpenWindow { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
    }
}
