//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dev_Position
    {
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<decimal> SubsidyFee { get; set; }
        public string WagesType { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<decimal> BaseScore { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
    }
}
