//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dev_PrinterTemplateDetail
    {
        public string PrinterTemplateDetail { get; set; }
        public string PrinterTemplateID { get; set; }
        public string ParameterName { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> LabelLeft { get; set; }
        public Nullable<decimal> LabelTop { get; set; }
        public Nullable<int> LabelType { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> FieldIndex { get; set; }
        public string CssAttribute { get; set; }
        public Nullable<bool> IsHead { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> RowIndex { get; set; }
        public Nullable<bool> AwayShow { get; set; }
        public Nullable<int> ContentFontSize { get; set; }
        public string Formatter { get; set; }
    }
}
