//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderProcess
    {
        public long ID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<decimal> ConfirmQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public string Unit { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string Manager { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string STEUS { get; set; }
        public string WorkingTimesID { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public int OutputQty1 { get; set; }
        public int BadQty1 { get; set; }
        public decimal TotalHour { get; set; }
        public string HourUnit { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string PreProcessID { get; set; }
        public string PreProcessName { get; set; }
        public Nullable<System.DateTime> PreStartDate { get; set; }
        public Nullable<System.DateTime> PreEndDate { get; set; }
        public Nullable<decimal> PreProducedQty { get; set; }
        public string NextProcessID { get; set; }
        public string NextProcessName { get; set; }
        public Nullable<System.DateTime> NextStartDate { get; set; }
        public Nullable<System.DateTime> NextEndDate { get; set; }
        public Nullable<decimal> NextProducedQty { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProcessGroupID { get; set; }
    }
}
