//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderForCheck
    {
        public long OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public decimal CheckProgress { get; set; }
        public long Scheduling { get; set; }
        public string ItemCode { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public string MachineID { get; set; }
        public string MachineName { get; set; }
    }
}
