//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_WorkShopInfo
    {
        public int OrganizeID { get; set; }
        public Nullable<int> OrganizeTypeID { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string OrganizeIDs { get; set; }
        public string WorkingTimesID { get; set; }
        public Nullable<int> TotalPeoples { get; set; }
        public string ManagerCode { get; set; }
        public string HRCode { get; set; }
        public string ERPOrderCode { get; set; }
        public string OrganizeSort { get; set; }
        public int LineCount { get; set; }
        public decimal TotalHours { get; set; }
        public decimal UsingHours { get; set; }
        public decimal RemainingHours { get; set; }
        public decimal CurrentHours { get; set; }
        public int WorkShopID { get; set; }
    }
}
