//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderBOMNoIssueQty
    {
        public long MaterialID { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public long OrderBOMID { get; set; }
    }
}
