//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_Material2
    {
        public long MaterialID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string Color { get; set; }
        public string Materials { get; set; }
        public Nullable<long> ParentMaterialID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string Model { get; set; }
        public string Trademark { get; set; }
        public string Code { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string CustomerCode { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public string Extend6 { get; set; }
        public string Extend7 { get; set; }
        public string Extend8 { get; set; }
        public string Extend9 { get; set; }
        public string Extend10 { get; set; }
        public string Extend11 { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public string Extend17 { get; set; }
        public string Extend18 { get; set; }
        public string Extend19 { get; set; }
        public string Extend20 { get; set; }
        public string Extend21 { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<int> FixedDay { get; set; }
        public string MaterialType { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public string Config1 { get; set; }
        public int ProcessCount { get; set; }
        public int CapacityCount { get; set; }
        public string ProcessGroupName { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> SafetyStockQty { get; set; }
        public Nullable<decimal> InventoryMaxLimitQty { get; set; }
        public Nullable<decimal> InventoryMinLimitQty { get; set; }
        public Nullable<decimal> SafetyStockPeriod { get; set; }
        public Nullable<decimal> UsingMonth { get; set; }
        public string ERPID { get; set; }
        public Nullable<decimal> Volume { get; set; }
    }
}
