//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderMissingAnalysis
    {
        public long ID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> HistoryQty { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<System.DateTime> OweDay { get; set; }
        public Nullable<decimal> RcvQty { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> CompletionQty { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> UnCompletionQty { get; set; }
        public Nullable<long> MaterialID { get; set; }
    }
}
