//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderPickingForStock
    {
        public string OrderNo { get; set; }
        public string Config1 { get; set; }
        public Nullable<int> AllPickCount { get; set; }
        public Nullable<int> PickedCount { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Color { get; set; }
        public string Extend1 { get; set; }
        public string MaterialType { get; set; }
        public string Extend3 { get; set; }
        public long OrderID { get; set; }
        public Nullable<decimal> Qty { get; set; }
    }
}
