//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingOutByMachine
    {
        public string 机台 { get; set; }
        public string 工单单号 { get; set; }
        public string 品名 { get; set; }
        public string 产品规格 { get; set; }
        public Nullable<decimal> 工单数量 { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> 产品点数 { get; set; }
        public Nullable<decimal> 白班计划 { get; set; }
        public Nullable<decimal> 白班产量 { get; set; }
        public Nullable<decimal> 晚班计划 { get; set; }
        public Nullable<decimal> 晚班产量 { get; set; }
        public Nullable<decimal> 累计产量 { get; set; }
        public Nullable<decimal> 余量 { get; set; }
        public Nullable<decimal> 计划产量 { get; set; }
        public Nullable<decimal> 实际产量 { get; set; }
        public Nullable<decimal> 计划点数 { get; set; }
        public Nullable<decimal> 实际点数 { get; set; }
        public string 产量达成率 { get; set; }
        public string 点数达成率 { get; set; }
        public string 原因 { get; set; }
        public string DeptName { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public string OrganizeIDs { get; set; }
    }
}
