//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_MaterialBOM
    {
        public long MaterialBomID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<long> BOMMasterID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<double> QPA { get; set; }
        public Nullable<decimal> ConsumptionRatio { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<double> BadRate { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public Nullable<bool> HairFeed { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<bool> IsCreateOrder { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public string MaterialName { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Code { get; set; }
        public string ProcessGroupID { get; set; }
    }
}
