//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderForScheduling
    {
        public long OrderID { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string SaleTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string SalesMan { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<int> OwnOrganizeID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> StockOutQty { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public string Extend6 { get; set; }
        public string Extend7 { get; set; }
        public string Extend8 { get; set; }
        public string Extend9 { get; set; }
        public string Extend10 { get; set; }
        public string Extend11 { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public string Extend17 { get; set; }
        public string Extend18 { get; set; }
        public string Extend19 { get; set; }
        public string Extend20 { get; set; }
        public string Extend21 { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Describe1 { get; set; }
        public string SourceOrderNo { get; set; }
        public Nullable<System.DateTime> ERPStartDate { get; set; }
        public Nullable<System.DateTime> ERPEndDate { get; set; }
        public string WorkOrderTypeID { get; set; }
        public Nullable<decimal> WGT { get; set; }
        public string PickingStatus { get; set; }
        public Nullable<long> ParentOrderID { get; set; }
        public Nullable<decimal> CompletionQty { get; set; }
        public string MaterialName { get; set; }
        public string Code { get; set; }
        public string Spec { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Materials { get; set; }
        public string MExtend1 { get; set; }
        public string MExtend2 { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public Nullable<decimal> PickingQty { get; set; }
        public string Config1 { get; set; }
        public string ControlID { get; set; }
        public Nullable<decimal> FeedingQty { get; set; }
        public string ERPID { get; set; }
        public Nullable<decimal> TotalScheduingQty { get; set; }
        public Nullable<decimal> NoSehcduingQty { get; set; }
        public Nullable<decimal> OweProducedQty { get; set; }
        public bool CompletionStatus { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> UnPackagedQty { get; set; }
        public Nullable<int> PackagedQty { get; set; }
        public Nullable<System.DateTime> ShipmentDay { get; set; }
        public Nullable<System.DateTime> ActualDay { get; set; }
        public Nullable<int> ContainerQty { get; set; }
        public string GroupCabinet { get; set; }
        public string SalesOrderDetailID { get; set; }
    }
}
