//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_ProcessGroupMaterialProcess
    {
        public string ProcessGroupMaterialID { get; set; }
        public string ProcessGroupID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string MaterialName { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public string SchedulingType { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<bool> IsAcquisition { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public string Unit { get; set; }
        public Nullable<long> OrderMaterialID { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public string PWSProcessID { get; set; }
        public string Code { get; set; }
        public string PWSProcessName { get; set; }
    }
}
