//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_ProcessPlanForSchedinngDetail
    {
        public long ProcessPartID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> FirstPlanID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<long> WorkShopID { get; set; }
        public string ProcessPartName { get; set; }
        public Nullable<decimal> PlanQty { get; set; }
        public Nullable<decimal> HasQty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> ExpectTime { get; set; }
        public Nullable<System.DateTime> DemandDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Batch { get; set; }
        public string PrepareStatus { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> AllocationStatus { get; set; }
        public string OrderNo { get; set; }
        public string Code { get; set; }
        public string Spec { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> LineID { get; set; }
        public string LineName { get; set; }
        public string ProcessID { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public Nullable<int> SN { get; set; }
        public string ERPID { get; set; }
        public string ERPDocNo { get; set; }
        public Nullable<System.DateTime> ERPDate { get; set; }
        public string WMSDocNo { get; set; }
        public Nullable<System.DateTime> PrepareDate { get; set; }
        public Nullable<decimal> AwaitQty { get; set; }
    }
}
