//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_ChildWorkingTimes
    {
        public string WorkingTimesID { get; set; }
        public string WorkingTimesName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ParentWorkingTimesID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string WorkingType { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public string Extend6 { get; set; }
        public string Extend7 { get; set; }
        public string Extend8 { get; set; }
        public string Extend9 { get; set; }
        public string Extend10 { get; set; }
        public string Extend11 { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public Nullable<decimal> WorkHour { get; set; }
        public Nullable<decimal> RestHour { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public string TimeScope { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CardNum { get; set; }
        public Nullable<int> IsPunch { get; set; }
        public Nullable<decimal> KnotRestHour { get; set; }
        public Nullable<decimal> LateOverTime { get; set; }
        public Nullable<decimal> LeaveOverTime { get; set; }
        public Nullable<decimal> LateOverTime2 { get; set; }
        public Nullable<decimal> LeaveOverTime2 { get; set; }
        public string EndTimeScope { get; set; }
        public Nullable<int> IsPunch2 { get; set; }
        public Nullable<decimal> OverTimeHour { get; set; }
    }
}
