//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderProgress
    {
        public long OrderID { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SaleTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string Trademark { get; set; }
        public string Unit { get; set; }
        public string StatusName { get; set; }
        public Nullable<decimal> OweProducedQty { get; set; }
        public Nullable<decimal> OweStockOutQty { get; set; }
        public string CustomerName { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public string WorkOrderTypeName { get; set; }
        public bool CompletionStatus { get; set; }
        public Nullable<decimal> PlanQty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
    }
}
