//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderBOM
    {
        public long OrderBOMID { get; set; }
        public Nullable<decimal> QPA { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> UnIssuedQty { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public string OrderNo { get; set; }
        public string WorkOrderTypeID { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> SchedulingQtyQPA { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public string HRCode { get; set; }
        public string OrganizeName { get; set; }
        public string WorkOrderTypeName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string DeptName { get; set; }
        public string DeptHRCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> Status { get; set; }
        public long OrderID { get; set; }
        public Nullable<decimal> WorkingQtyQPA { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
    }
}
