//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderForProcess
    {
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string MaterialName { get; set; }
        public string Code { get; set; }
        public string ProcessName { get; set; }
        public string ProcessID { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<int> StandardPeoples { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<decimal> UnSchedulingQty { get; set; }
        public string SchedulingType { get; set; }
        public long OrderID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Priority { get; set; }
        public long MaterialID { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public Nullable<bool> IsAcquisition { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public string Unit { get; set; }
        public string ProcessGroupID { get; set; }
        public Nullable<bool> MaterialIsScheduling { get; set; }
        public Nullable<decimal> WGT { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string Spec { get; set; }
        public string OrganizeIDs { get; set; }
        public string OrganizeName { get; set; }
        public int TotalBoms { get; set; }
        public Nullable<decimal> TotalPoints { get; set; }
        public string MachineID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<decimal> SchedulingQtyPre { get; set; }
        public Nullable<decimal> OweAllQty { get; set; }
        public Nullable<decimal> AllOutputQty { get; set; }
        public string PostProcessID { get; set; }
        public Nullable<int> FixDay { get; set; }
        public Nullable<System.DateTime> StartDateNext { get; set; }
        public string NextProcessName { get; set; }
        public string ControlID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public string ProcessArea { get; set; }
        public Nullable<decimal> AllPreProducedQty { get; set; }
        public Nullable<decimal> AllNextProducedQty { get; set; }
        public string StatusName { get; set; }
        public string Remark2 { get; set; }
    }
}
