//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingOutByOrganizePrice
    {
        public string DeptName { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<decimal> WorkingQty { get; set; }
        public decimal WorkingQtyPrice { get; set; }
        public decimal OutputQtyPrice { get; set; }
        public string OrganizeIDs { get; set; }
    }
}
