//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingRule
    {
        public string SchedulingRuleID { get; set; }
        public string Name { get; set; }
        public string ParameterName { get; set; }
        public Nullable<int> DictionaryID { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public string SQLQuery { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string MachineIDs { get; set; }
        public string OrganizeIDs { get; set; }
    }
}
