//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingForERP
    {
        public Nullable<long> OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string WorkOrderTypeID { get; set; }
        public string HRCode { get; set; }
        public string OrganizeName { get; set; }
        public string WorkOrderTypeName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public long Scheduling { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public string DeptName { get; set; }
        public string DeptHRCode { get; set; }
    }
}
