//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderBOMNew
    {
        public long OrderBOMID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public long OrderID { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> QPA { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public Nullable<decimal> UnIssuedQty { get; set; }
        public string Extend1 { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<decimal> RcvQty { get; set; }
        public Nullable<decimal> OnlineQty { get; set; }
        public Nullable<decimal> OnloadQty { get; set; }
        public Nullable<decimal> OncheckQty { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductSepc { get; set; }
        public Nullable<long> ProductMaterialID { get; set; }
        public string LGORT { get; set; }
        public string RGEKZ { get; set; }
        public string RSPOS { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public string ItemNo { get; set; }
        public string XLOEK { get; set; }
        public string POTracker { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public int ProductionStatus { get; set; }
        public string IssueStatus { get; set; }
        public string IssueType { get; set; }
        public string ERPID { get; set; }
        public string SupplyWh { get; set; }
        public Nullable<decimal> CompletionQty { get; set; }
        public Nullable<decimal> UnCompletionQty { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string Color { get; set; }
        public Nullable<bool> HairFeed { get; set; }
        public Nullable<decimal> NoSehcduingQty { get; set; }
        public string LineNum { get; set; }
        public string APSIssueType { get; set; }
    }
}
