//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderPlanMaterialFormList
    {
        public long MaterialFormID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string Code { get; set; }
        public string Spec { get; set; }
        public string MaterialName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public Nullable<long> FirstPlanID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> FormQty { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<decimal> QPA { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> StockQtyAllocation { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public Nullable<int> StockState { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string POTracker { get; set; }
        public Nullable<decimal> PlanQty { get; set; }
        public Nullable<decimal> OncheckQty { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string PODocs { get; set; }
        public string SourceOrderNo { get; set; }
        public string WorkShopName { get; set; }
        public Nullable<decimal> OnloadQty { get; set; }
        public Nullable<long> OrderBOMID { get; set; }
        public string POSuplierName { get; set; }
        public string WorkOrderTypeName { get; set; }
        public string MaterialProp { get; set; }
        public string IssueType { get; set; }
    }
}
