//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_Machine
    {
        public string MachineID { get; set; }
        public string MachineModel { get; set; }
        public string MachineName { get; set; }
        public string MachineTypeID { get; set; }
        public Nullable<int> MachineCapacity { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Tonnage { get; set; }
        public string MachineCode { get; set; }
        public Nullable<int> WorkingStatus { get; set; }
        public string ConfigMachine { get; set; }
        public Nullable<int> ProcessCount { get; set; }
        public string OrganizeName { get; set; }
        public string OrganizeIDs { get; set; }
        public Nullable<int> MouldCount { get; set; }
        public string ConfigRules { get; set; }
        public Nullable<int> BasePoints { get; set; }
        public Nullable<int> BaseMinute { get; set; }
        public Nullable<int> BaseMinuteNew { get; set; }
    }
}
