//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingAll
    {
        public long OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string MaterialName { get; set; }
        public string Code { get; set; }
        public string Spec { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ControlID { get; set; }
        public string MaterialType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ProcessID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<long> Scheduling { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
    }
}
