//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_Scheduling
    {
        public long Scheduling { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<int> CurrentPeoples { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public string Extend6 { get; set; }
        public string Extend7 { get; set; }
        public string Extend8 { get; set; }
        public string Extend9 { get; set; }
        public string Extend10 { get; set; }
        public string Extend11 { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public string Extend17 { get; set; }
        public string Extend18 { get; set; }
        public string Extend19 { get; set; }
        public string Extend20 { get; set; }
        public string Extend21 { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SalesMan { get; set; }
        public string SaleTo { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public string MaterialName { get; set; }
        public string Materials { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string Trademark { get; set; }
        public string Unit { get; set; }
        public string StatusName { get; set; }
        public string ProcessName { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public string OrganizeIDs { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<int> StandardPeoples { get; set; }
        public Nullable<decimal> StandardCapacity { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<decimal> CapacityLoad { get; set; }
        public string MachineID { get; set; }
        public string SchedulingType { get; set; }
        public Nullable<int> MachineName { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public string DeptName { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<int> HourCapacity { get; set; }
        public Nullable<decimal> StandardHourCapacity { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Picking { get; set; }
        public Nullable<decimal> OweAllQty { get; set; }
        public string SourceOrderNo { get; set; }
        public Nullable<decimal> SFGQty { get; set; }
        public Nullable<decimal> SFGQtyed { get; set; }
        public Nullable<decimal> OweSFGQty { get; set; }
        public Nullable<decimal> AllDemand { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> StockQtyByChecked { get; set; }
        public string WorkOrderTypeName { get; set; }
        public string ControlID { get; set; }
        public Nullable<decimal> PreProducedQty { get; set; }
        public Nullable<decimal> NextProducedQty { get; set; }
        public string OrganizeSort { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
    }
}
