//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_ProcessMaterialError
    {
        public string ProcessMaterial { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> StandardPeoples { get; set; }
        public Nullable<decimal> Points { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ProcessNum { get; set; }
        public Nullable<int> TotalBoms { get; set; }
        public Nullable<int> TotalMaterials { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> Seconds { get; set; }
        public string PWSProcessID { get; set; }
    }
}
