//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingDetail
    {
        public long SchedulingDetail { get; set; }
        public Nullable<long> Scheduling { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<decimal> WorkingQty { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public string AuditAccount { get; set; }
        public string AuditAccountName { get; set; }
        public string NextAccounts { get; set; }
        public string NextAccountNames { get; set; }
        public string AuditAccountLog { get; set; }
        public string AuditAccountNameLog { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SalesMan { get; set; }
        public string SaleTo { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public string MaterialName { get; set; }
        public string Materials { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string Trademark { get; set; }
        public string Unit { get; set; }
        public string StatusName { get; set; }
        public string ProcessName { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public string ProcessID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public string OrganizeIDs { get; set; }
        public Nullable<int> Priority { get; set; }
        public string WorkingTimesID { get; set; }
        public string MachineID { get; set; }
        public string SchedulingType { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public long OrderID { get; set; }
        public Nullable<int> MoldHole { get; set; }
        public Nullable<decimal> MouldTonnage { get; set; }
        public string MachineName { get; set; }
        public string WorkingTimesName { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> CurrentPeoples { get; set; }
        public string MoldName { get; set; }
        public string MoldNO { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SchedulingStatus { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public string MachineMouldID { get; set; }
        public Nullable<decimal> OweAllQty { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public string Extend10 { get; set; }
        public string Rate { get; set; }
        public Nullable<decimal> CleanQty { get; set; }
        public Nullable<decimal> SFGQtyed { get; set; }
        public Nullable<decimal> SFGQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public string WorkOrderTypeName { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsAutoScheduling { get; set; }
        public string ProcessGroupID { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public Nullable<bool> ExtraYield { get; set; }
        public Nullable<bool> IsAcquisition { get; set; }
    }
}
