//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingDetailForOutput
    {
        public long SchedulingDetail { get; set; }
        public Nullable<long> Scheduling { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<decimal> WorkingQty { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public string AuditAccount { get; set; }
        public string AuditAccountName { get; set; }
        public string NextAccounts { get; set; }
        public string NextAccountNames { get; set; }
        public string AuditAccountLog { get; set; }
        public string AuditAccountNameLog { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SalesMan { get; set; }
        public string SaleTo { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public string MaterialName { get; set; }
        public string Materials { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string Trademark { get; set; }
        public string Unit { get; set; }
        public string StatusName { get; set; }
        public string ProcessName { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public string ProcessID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<decimal> SFGQty { get; set; }
    }
}
