//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderForMakeByOrderSMT
    {
        public long OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string ControlID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> FeedingQty { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public string MaterialName { get; set; }
        public string Materials { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string Trademark { get; set; }
        public string Unit { get; set; }
        public Nullable<long> ProcessMaterialID { get; set; }
        public string OrganizeIDs { get; set; }
        public string ProcessGroupID { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public Nullable<decimal> AllOutputQty { get; set; }
        public Nullable<decimal> AllSchedulingQty { get; set; }
        public Nullable<decimal> UnAllSchedulingQty { get; set; }
        public string SchedulingStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<System.DateTime> StartDateNext { get; set; }
        public string ProcessGroupName { get; set; }
    }
}
