//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_ProcessPlan
    {
        public long ProcessPlanID { get; set; }
        public long ProcessPartID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<long> FirstPlanID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> PlanQty { get; set; }
        public Nullable<decimal> HasQty { get; set; }
        public Nullable<decimal> ExpectTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> WorkShopID { get; set; }
        public Nullable<long> LineID { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string OrderNo { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public int OutputQty { get; set; }
        public int BadQty { get; set; }
        public string Operation { get; set; }
        public string WorkShopName { get; set; }
        public string LineName { get; set; }
        public string Model { get; set; }
        public string ProcessID { get; set; }
        public Nullable<decimal> Coefficient { get; set; }
        public string ManagerCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public Nullable<decimal> STD { get; set; }
        public string ProcessPartName { get; set; }
        public string CustomerName { get; set; }
        public string isDelete { get; set; }
        public string Extend4 { get; set; }
        public string StatusName { get; set; }
        public Nullable<decimal> ProductionSchedule { get; set; }
        public Nullable<decimal> CompletedQuantity { get; set; }
        public Nullable<decimal> PartQuantity { get; set; }
        public Nullable<decimal> ProcedureSchedule { get; set; }
        public string ProcessGroupName { get; set; }
        public string IssueType { get; set; }
        public Nullable<decimal> ProcessPartQty { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public string Color { get; set; }
        public Nullable<int> TotalPeoples { get; set; }
        public string Extend8 { get; set; }
        public string SourceOrderNo { get; set; }
        public string PrepareStatus { get; set; }
        public string ERPID { get; set; }
        public string ERPDocNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> PreparedQty { get; set; }
        public Nullable<System.DateTime> ERPDate { get; set; }
        public string SaleTo { get; set; }
        public string OrderRemark { get; set; }
        public Nullable<System.DateTime> WorkShopStartDate { get; set; }
        public Nullable<System.DateTime> WorkShopEndDate { get; set; }
    }
}
