//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_OrderForDown
    {
        public long OrderID { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SaleTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string SalesMan { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<int> OwnOrganizeID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public Nullable<int> ProductionStatus { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> StockOutQty { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Describe1 { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public string MaterialName { get; set; }
        public string Materials { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string Trademark { get; set; }
        public string Unit { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> OweProducedQty { get; set; }
        public Nullable<decimal> OweStockOutQty { get; set; }
        public string CustomerName { get; set; }
        public string OrganizeName { get; set; }
        public string OrganizeIDs { get; set; }
        public string Extend8 { get; set; }
        public string Extend12 { get; set; }
        public string Extend1 { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> SchedulingQty { get; set; }
        public string Extend10 { get; set; }
        public string Extend9 { get; set; }
        public string LineName { get; set; }
    }
}
