//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_ProcessGroupInfo
    {
        public string ProcessGroupInfoID { get; set; }
        public string ProcessID { get; set; }
        public string ProcessGroupID { get; set; }
        public Nullable<bool> IsScheduling { get; set; }
        public Nullable<bool> IsAcquisition { get; set; }
        public Nullable<int> AcquisitionTimes { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public Nullable<bool> IsPerson { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public string ProductionProcessID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<int> ProcessingTimes { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string ProcessName { get; set; }
        public string ProcessGroupName { get; set; }
        public string OutputType { get; set; }
        public string PostProcessID { get; set; }
        public string SchedulingType { get; set; }
        public Nullable<int> FixDay { get; set; }
        public string PostConstraint { get; set; }
        public Nullable<bool> ExtraYield { get; set; }
        public string ProcessPartName { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
