//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APS_SchedulingForOutput
    {
        public Nullable<long> OrderID { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public string OutputType { get; set; }
        public long Scheduling { get; set; }
        public Nullable<decimal> ProducedQtyP { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string OrderNo { get; set; }
        public string MachineName { get; set; }
        public string OrganizeName { get; set; }
        public string MaterialName { get; set; }
        public string Code { get; set; }
    }
}
