//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Dev_ButtonMenuRoleMapRead
    {
        public int ID { get; set; }
        public Nullable<int> ButtonMenuMapID { get; set; }
        public string RoleID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string WorkFlowInstanceID { get; set; }
        public Nullable<int> Status { get; set; }
        public string MenuCode { get; set; }
        public Nullable<int> ButtonID { get; set; }
        public string ButtonCode { get; set; }
        public string ButtonName { get; set; }
        public string OnClick { get; set; }
        public string FormUrl { get; set; }
        public string MenuName { get; set; }
        public string Icon { get; set; }
        public string ButtonType { get; set; }
    }
}
