//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Dev_RoleMenuMap
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> ID { get; set; }
        public string UIIsCheck { get; set; }
        public string RoleID { get; set; }
        public string ParentCode { get; set; }
        public Nullable<int> MenuMapButton { get; set; }
        public Nullable<bool> IsAllVisible { get; set; }
    }
}
