//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Dev_ButtonMenuRoleMap
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ButtonMenuMapID { get; set; }
        public string UIIsCheck { get; set; }
        public string RoleID { get; set; }
        public Nullable<int> ID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string ButtonName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ParentCode { get; set; }
        public string RealMenuCode { get; set; }
        public Nullable<bool> IsAllVisible { get; set; }
        public Nullable<int> ViewSort { get; set; }
    }
}
