//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_SSNScan
    {
        public string SSN { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string MachineID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<System.DateTime> ScanOn { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public int MoldHole { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public string Extend6 { get; set; }
        public string Extend7 { get; set; }
        public string Extend8 { get; set; }
        public string Extend9 { get; set; }
        public string Extend10 { get; set; }
        public string Extend11 { get; set; }
        public string Extend12 { get; set; }
        public string Extend13 { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public string OrderNo { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string MachineName { get; set; }
        public Nullable<decimal> ZxQuantity { get; set; }
    }
}
