//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_SSN
    {
        public string SSN { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> OrderPrintID { get; set; }
        public Nullable<int> TeplateMaterialID { get; set; }
        public Nullable<decimal> UnitQty { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> PrintedQty { get; set; }
        public Nullable<int> CreatedQty { get; set; }
        public string TeplateName { get; set; }
        public string MaterialName { get; set; }
        public string Code { get; set; }
        public string Model { get; set; }
        public string SSNDate { get; set; }
        public string CustomerCode { get; set; }
        public string SPEC { get; set; }
        public string ItemCustomerCode { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public int IsPrintCount { get; set; }
        public string PrintContent { get; set; }
        public Nullable<decimal> ZxQuantity { get; set; }
        public string SourceBillNo { get; set; }
        public Nullable<int> PackageQty { get; set; }
        public Nullable<long> MaterialID { get; set; }
    }
}
