//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_OrderOutputByOrderForCheck
    {
        public long OrderOutputByOrderID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string SSN { get; set; }
        public string SSN2 { get; set; }
        public string SSN3 { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string ExceptionTypeID { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string BatchNO { get; set; }
        public string WarehouseID { get; set; }
        public Nullable<long> SchedulingDetail { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string OrderNo { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string Code { get; set; }
        public string StatusName { get; set; }
    }
}
