//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_OrderOutput
    {
        public long SchedulingDetail { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<long> OrderYieldID { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public long OrderID { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<decimal> WorkingQty { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string OrderNo { get; set; }
        public string MaterialName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string ProcessID { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public string ProcessName { get; set; }
        public string OrganizeName { get; set; }
        public string EasyUIRowState { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<long> Scheduling { get; set; }
        public string OrganizeIDs { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string MachineName { get; set; }
        public string Spec { get; set; }
        public string WorkingTimesName { get; set; }
        public string WorkingTimesID { get; set; }
        public string SchedulingType { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> OweQty { get; set; }
        public string Remark1 { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<int> CurrentPeoples { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<decimal> OweAllQty { get; set; }
        public Nullable<decimal> SFGQty { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public string ProcessGroupInfoID { get; set; }
        public string ProcessGroupID { get; set; }
        public string Extend10 { get; set; }
        public Nullable<decimal> SFGQtyed { get; set; }
        public Nullable<decimal> Coefficient { get; set; }
        public Nullable<decimal> CoefficientQty { get; set; }
        public Nullable<decimal> ReworkCoefficient { get; set; }
        public Nullable<int> ReworkPeoples { get; set; }
        public Nullable<decimal> ReworkTotalHour { get; set; }
        public string Rate { get; set; }
        public string OutputType { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> AbnormalProductivity { get; set; }
        public Nullable<decimal> TotalProductivity { get; set; }
        public string WorkOrderTypeName { get; set; }
        public Nullable<decimal> DayEfficiency { get; set; }
        public Nullable<decimal> CleanQty { get; set; }
        public Nullable<bool> IsProduction { get; set; }
        public string MachineID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<decimal> FeedingTime { get; set; }
        public Nullable<decimal> TuningProgram1 { get; set; }
        public Nullable<decimal> TuningProgram2 { get; set; }
        public Nullable<decimal> TuningLine1 { get; set; }
        public Nullable<decimal> TuningLine2 { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<int> ViewSort { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public Nullable<int> ERPStatus { get; set; }
        public string HourUnit { get; set; }
        public string ERPProcessID { get; set; }
        public string Unit { get; set; }
    }
}
