//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_OrderOutputPersonsNoAudit
    {
        public long OrderOutputPersonsID { get; set; }
        public Nullable<long> OrderYieldID { get; set; }
        public string ProcessID { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public string Names { get; set; }
        public string Accounts { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string AuditName { get; set; }
        public Nullable<System.DateTime> AuditOn { get; set; }
        public Nullable<System.DateTime> OutputDate { get; set; }
        public string PWSProcessID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string WagesModel { get; set; }
        public string WagesRemark { get; set; }
        public Nullable<decimal> WagesQty { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public Nullable<decimal> HourPrice { get; set; }
        public Nullable<decimal> OutputQtyCheck { get; set; }
        public string WeighingQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string AccountGroupID { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<decimal> TimeSpent { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<long> SchedulingDetail { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProcessingTimes { get; set; }
        public Nullable<long> Scheduling { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public string OrganizeIDs { get; set; }
        public string Code { get; set; }
        public string StatusName { get; set; }
        public string OrderNo { get; set; }
        public string MaterialName { get; set; }
        public string ProcessName { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> SFGQty { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<bool> Continuity { get; set; }
        public Nullable<int> Peoples { get; set; }
        public string HoursRemark { get; set; }
    }
}
