//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_OrderOutputForOrder
    {
        public Nullable<int> OutputQty { get; set; }
        public long OrderID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> BadQty { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string Code { get; set; }
        public string OrderNo { get; set; }
        public string CustomerName { get; set; }
        public string Remark2 { get; set; }
        public string Peoples { get; set; }
        public string Machines { get; set; }
        public string QC { get; set; }
        public Nullable<int> ProcessPriority { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string SSNID { get; set; }
    }
}
