//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MES_AccountGroupOutputDetail
    {
        public int AccountGroupOutputDetailID { get; set; }
        public string AccountGroupID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public string ProcessID { get; set; }
        public string WagesModel { get; set; }
        public string WagesRemark { get; set; }
        public Nullable<decimal> WagesQty { get; set; }
        public Nullable<int> Status { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public Nullable<decimal> HourPrice { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<decimal> OutputQtyCheck { get; set; }
        public Nullable<long> OrganizeID { get; set; }
        public Nullable<System.DateTime> OutputDate { get; set; }
        public string WeighingQty { get; set; }
        public string AccountGroupName { get; set; }
        public string OrganizeName { get; set; }
        public string ProcessName { get; set; }
        public string MaterialName { get; set; }
        public string Code { get; set; }
        public string AccountGroupOutputID { get; set; }
        public string Accounts { get; set; }
        public string StatusName { get; set; }
    }
}
