//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PWS_AttendanceDayError
    {
        public string ID { get; set; }
        public string YearMonth { get; set; }
        public Nullable<System.DateTime> Ddate { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public long OrganizeID { get; set; }
        public string OrganizeName { get; set; }
        public string WorkingTimesID { get; set; }
        public string WorkingTimesNo { get; set; }
        public string PostID { get; set; }
        public string Zhiji { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StartWorkTime { get; set; }
        public Nullable<System.DateTime> EndWorkTime { get; set; }
        public Nullable<decimal> LateHour { get; set; }
        public Nullable<decimal> LeaveHour { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Status1 { get; set; }
        public Nullable<int> Status2 { get; set; }
        public Nullable<int> AttendanceResult { get; set; }
        public Nullable<int> IsAbnormal { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<decimal> Days { get; set; }
        public Nullable<decimal> ShouldHours { get; set; }
        public Nullable<decimal> NormaltimeHours { get; set; }
        public Nullable<decimal> OvertimeHours { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public string AttendanceType { get; set; }
        public Nullable<decimal> ShouldDays { get; set; }
        public Nullable<decimal> AbsenteeismDays { get; set; }
        public Nullable<decimal> LeaveMinutes { get; set; }
        public Nullable<decimal> LateMinutes { get; set; }
        public Nullable<decimal> AbnormalMinutes { get; set; }
    }
}
