//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PWS_WorkingTimes
    {
        public string WorkingTimesID { get; set; }
        public string ParentWorkingTimesID { get; set; }
        public string WorkingTimesName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string TimeScope { get; set; }
        public string EndTimeScope { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CardNum { get; set; }
        public string ParentWorkingTimesName { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<decimal> WorkHour { get; set; }
        public Nullable<decimal> RestHour { get; set; }
        public Nullable<decimal> OverHour { get; set; }
        public string WorkingType { get; set; }
        public int IsPunch { get; set; }
        public decimal KnotRestHour { get; set; }
        public decimal LateOverTime { get; set; }
        public decimal LeaveOverTime { get; set; }
        public decimal LateOverTime2 { get; set; }
        public decimal LeaveOverTime2 { get; set; }
        public Nullable<int> ChildCardNum { get; set; }
        public string ParentTimeScope { get; set; }
        public string EndWorkingType { get; set; }
        public int EndIsPunch { get; set; }
        public decimal EndRestHour { get; set; }
        public decimal EndKnotResHour { get; set; }
        public decimal EndLateOverTime { get; set; }
        public decimal EndLeaveOverTime { get; set; }
        public decimal EndLateOverTime2 { get; set; }
        public decimal EndLeaveOverTime2 { get; set; }
        public Nullable<int> EndChildCardNum { get; set; }
        public string EndWorkingTimesID { get; set; }
    }
}
