//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PWS_WJDayWages
    {
        public Nullable<long> OrganizeID { get; set; }
        public Nullable<int> WorkShopID { get; set; }
        public Nullable<System.DateTime> Ddate { get; set; }
        public string Area { get; set; }
        public string WorkShopName { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string WagesModel { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public string WagesType { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public Nullable<decimal> DayWages { get; set; }
    }
}
