//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PWS_ResignBill
    {
        public string BillID { get; set; }
        public Nullable<long> OrganizeID { get; set; }
        public string YearMonth { get; set; }
        public Nullable<int> BillStatus { get; set; }
        public Nullable<System.DateTime> BillStatusDate { get; set; }
        public string WorkFlowID { get; set; }
        public Nullable<int> ResignType { get; set; }
        public Nullable<int> ResignQty { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyedBy { get; set; }
        public string ModifyedByName { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string OrganizeName { get; set; }
    }
}
