//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PWS_DailyWage
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Ddate { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> OrganizeID { get; set; }
        public string OrganizeName { get; set; }
        public string YearMonth { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public string WagesType { get; set; }
        public Nullable<decimal> AssignWork { get; set; }
        public Nullable<decimal> DayWages { get; set; }
        public string AccountGroupID { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string AccountGroupName { get; set; }
        public Nullable<decimal> HourWages { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public string WagesModel { get; set; }
    }
}
