//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserWorkingTimes
    {
        public string Account { get; set; }
        public string Name { get; set; }
        public string ParentWorkingTimesID { get; set; }
        public string ParentWorkingTimesName { get; set; }
        public int OrganizeID { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public string WorkingType { get; set; }
        public string WorkingTimesID { get; set; }
        public string WorkingTimesName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> CardNum { get; set; }
        public Nullable<int> IsPunch { get; set; }
        public Nullable<int> IsPunch2 { get; set; }
        public string TimeScope { get; set; }
        public string EndTimeScope { get; set; }
        public Nullable<decimal> WorkHour { get; set; }
        public Nullable<decimal> RestHour { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<decimal> KnotRestHour { get; set; }
        public Nullable<decimal> LateOverTime { get; set; }
        public Nullable<decimal> LeaveOverTime { get; set; }
        public Nullable<decimal> LateOverTime2 { get; set; }
        public Nullable<decimal> LeaveOverTime2 { get; set; }
    }
}
