//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Wages_DayWages
    {
        public string Account { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> OutputQty { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalWages { get; set; }
        public Nullable<decimal> Days { get; set; }
        public string FeeType { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string WagesType { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<decimal> SubsidyFee { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
    }
}
