//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_StockOut
    {
        public string StockOutID { get; set; }
        public string StockID { get; set; }
        public Nullable<System.DateTime> StockOutDate { get; set; }
        public string StockOutTo { get; set; }
        public string StockOutSSN { get; set; }
        public Nullable<decimal> StockOutQty { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string DeliveryPlanID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> ProducedQty { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> AllStockOutQty { get; set; }
        public Nullable<int> MFGOrganizeID { get; set; }
        public string Spec { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Config1 { get; set; }
    }
}
