//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_ReceiptDetail
    {
        public string ReceiptDetailID { get; set; }
        public string ReceiptID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<float> ReceiptQty { get; set; }
        public Nullable<decimal> BadQty { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<float> TotalPrice { get; set; }
        public Nullable<int> OrganizeID { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string WarehouseID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string SupplierName { get; set; }
        public string MaterialName { get; set; }
        public string WarehouseName { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public string Color { get; set; }
        public string Extend3 { get; set; }
        public string Extend1 { get; set; }
        public string MaterialType { get; set; }
        public Nullable<float> StockQty { get; set; }
        public Nullable<decimal> OnloadQty { get; set; }
        public string Code { get; set; }
        public string ReceiptMark { get; set; }
        public string WarehouseCode { get; set; }
        public string DeliveryID { get; set; }
        public string Extend2 { get; set; }
    }
}
