//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_StockForPicking
    {
        public string StockID { get; set; }
        public string WarehouseID { get; set; }
        public long MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<long> MFGOrganizeID { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string SSN { get; set; }
        public Nullable<long> OrderOutputByOrderID { get; set; }
        public Nullable<decimal> InQty { get; set; }
        public string ERPID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CustomerName { get; set; }
        public string WarehouseName { get; set; }
        public string SSN2 { get; set; }
        public string MaterialCode { get; set; }
        public string ParentWarehouseName { get; set; }
        public string ParentWarehouseID { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public string CustomerCode { get; set; }
        public string Code { get; set; }
        public Nullable<int> IssuedQty { get; set; }
        public string Code1 { get; set; }
        public Nullable<decimal> OncheckQty { get; set; }
    }
}
