//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_WarehouseByStock
    {
        public string WarehouseID { get; set; }
        public string ParentWarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public string MaterialName { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public string ParentWarehouseName { get; set; }
        public string SSN { get; set; }
    }
}
