//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_DeliveryPlanForNew
    {
        public string DeliveryPlanID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public Nullable<float> DeliveryQty { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
        public string DeliveryPlanHeadID { get; set; }
        public string CustomerName { get; set; }
        public string Tel { get; set; }
        public string Contact { get; set; }
        public string Spec { get; set; }
        public string Unit { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Remark1 { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string Address { get; set; }
        public Nullable<float> DeliveryQty2 { get; set; }
        public string SaleManName { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<decimal> DeliveryedQty { get; set; }
        public string Remark2 { get; set; }
        public string Config1 { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<System.DateTime> DeliveryPlanDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Color { get; set; }
        public string Extend2 { get; set; }
        public string ReceiptMark { get; set; }
    }
}
