//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_StockForInOut
    {
        public string StockID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> InQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByName { get; set; }
        public string DataType { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> InCreatedOn { get; set; }
        public string Remark1 { get; set; }
        public Nullable<System.DateTime> OutCreatedOn { get; set; }
        public string OutCreatedByName { get; set; }
        public string Extend1 { get; set; }
        public string MaterialType { get; set; }
        public string Code { get; set; }
        public string Extend3 { get; set; }
        public string Color { get; set; }
        public string ReceiptRemark { get; set; }
    }
}
