//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManufacture.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WorkingTimes
    {
        public string WorkingTimesID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Ttime1 { get; set; }
        public string Ttime2 { get; set; }
        public string Ttime3 { get; set; }
        public string Ttime4 { get; set; }
        public string Ttime5 { get; set; }
        public string Ttime6 { get; set; }
    }
}
