// <auto-generated>由 scripts/Migrate-MSSQLCore.ps1 生成；EnableLegacyApsCoreSource=true 时编译。</auto-generated>
using EasyManufacture.Entitys;
using EasyManufacture.Licence;
using Newtonsoft.Json.Linq;
using System.Collections.Specialized;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Globalization;
using System.Text;
using QueryMethod = EasyManufacture.Infrastructure.Legacy.MssqlQueryMethods.QueryMethod;

using Org.BouncyCastle.Asn1.Ocsp;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;



namespace EasyManufacture.Infrastructure.Legacy
{
    /// <summary>
    /// 数据库快捷类
    /// 作者：易制造
    /// 日期：2018-06-04
    public class MSSQLCore
    {

        /// <summary>
        /// 无参数构造函数，此构造函数无法调用生成SQL语句
        /// </summary>
        public MSSQLCore()
        {
            CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("zh-CN", true) { DateTimeFormat = { ShortDatePattern = "yyyy-MM-dd", FullDateTimePattern = "yyyy-MM-dd HH:mm:ss", LongTimePattern = "HH:mm:ss" } };
        }
        /// <summary>
        /// 根据数据字典表初始化
        /// </summary>
        /// <param name="dictionaryID">数据字典ID</param>
        /// <param name="jsToken">客户端的值</param>
        /// <param name="prefix">客户端前缀</param>
        public MSSQLCore(int dictionaryID, JToken jsToken, string prefix = "")
        {
           
            this.Prefix = prefix;
            JsToken = jsToken;
            getDicitionary(dictionaryID);
         
        }
        /// <summary>
        /// 是否启用OR查询
        /// </summary>
        public bool IsUserOR
        {
            get;set;
        }
        /// <summary>
        /// 对象标题
        /// </summary>
        public string ObjectText
        {
            get; set;
        }
        /// <summary>
        /// 更新前执行的SQL
        /// </summary>
        public string BeforeUpdate
        {
            get; set;
        }
        /// <summary>
        /// 更新后执行的SQL
        /// </summary>
        public string AfterUpdate
        {
            get; set;
        }
        /// <summary>
        /// 更新前执行的SQL
        /// </summary>
        public string BeforeAdd
        {
            get; set;
        }
        /// <summary>
        /// 添加后执行的SQL
        /// </summary>
        public string AfterAdd
        {
            get; set;
        }
        /// <summary>
        /// 固定条件
        /// </summary>
        public string Condition
        {
            get; set;
        }
        public string AfterDelete
        {
            get;set;
        }
        private void getDicitionary(int dictionaryID)
        {
            DictionaryID = dictionaryID;
            DataTable dtDictionary = SqlHelper.ExecuteDataTable(@"select A.*,B.ObjectName,B.TabelName,b.ObjectText,B.AfterUpdate,B.BeforeUpdate
 ,B.AfterAdd,B.Condition
,B.BeforeAdd,B.AfterDelete
FROM Dev_DictionaryField(nolock) A
  INNER JOIN Dev_Dictionary(nolock) B ON A.DictionaryID=B.DictionaryID
where A.DictionaryID=" + dictionaryID + " AND A.IsSelect=1 ORDER BY A.FieldIndex");
            this.DtDictionary = dtDictionary;
            this.SqlParameters = new SqlParameter[DtDictionary.Rows.Count];

            if (DtDictionary.Rows.Count > 0)
            {
                 
                ObjectName = dtDictionary.Rows[0]["ObjectName"].ToString();
                TabelName = dtDictionary.Rows[0]["TabelName"].ToString();
                ObjectText = dtDictionary.Rows[0]["ObjectText"].ToString();
                AfterUpdate = dtDictionary.Rows[0]["AfterUpdate"].ToString();
                AfterDelete= dtDictionary.Rows[0]["AfterDelete"].ToString();
                BeforeUpdate = dtDictionary.Rows[0]["BeforeUpdate"].ToString();
                AfterAdd = dtDictionary.Rows[0]["AfterAdd"].ToString();
                Condition = "  "+ReplaceSQL(dtDictionary.Rows[0]["Condition"].ToString());
                BeforeAdd = dtDictionary.Rows[0]["BeforeAdd"].ToString();


                if (string.IsNullOrEmpty(TabelName))
                {
                    TabelName = ObjectName;
                }
            }
            if (string.IsNullOrEmpty(ObjectName))
            {
                throw new Exception("未找到操作对象");
            }
        }
        /// <summary>
        /// 客户端控件前缀
        /// </summary>
        public string Prefix
        {
            get; set;
        }
        public string OrderBy
        {
            get; set;
        }

        /// <summary>
        /// 根据数据字典表初始化
        /// </summary>
        /// <param name="dictionaryID">数据字典ID</param>
        /// <param name="nameValueCollection">客户端的值</param>
        /// <param name="prefix">控件前缀</param>
        /// <param name="account">当前的账号信息</param>
        public MSSQLCore(int dictionaryID, NameValueCollection nameValueCollection, string prefix = "", string where = "", string account = "", string orderBy = "")
        {
            Where = where;
            this.Prefix = prefix;
            this.Account = account;
            this.NameValueCollection = nameValueCollection;
            OrderBy = orderBy;
            getDicitionary(dictionaryID);
        }
        /// <summary>
        /// 当前请求的账号信息
        /// </summary>
        public string Account
        {
            get; set;
        }
        /// <summary>
        /// 自定义条件
        /// </summary>
        public string Where
        {
            get; set;
        }
        public int DictionaryID
        {
            get; set;
        }
        /// <summary>
        /// 操作的对象
        /// </summary>
        private string ObjectName
        {
            get; set;
        }
        /// <summary>
        /// 操作的表名
        /// </summary>
        private string TabelName
        {
            get; set;
        }
        private string keyValue = "";
        /// <summary>
        /// 主键值
        /// </summary>
        public string KeyValue
        {
            get
            {
                return keyValue;
            }
        }
        public static List<string> ListSystemField
        {
            get
            {
                return new List<string> { "CreatedOn", "ModifyedOn", "CreatedBy", "CreatedByName", "ModifiedBy", "ModifiedByName" };
            }
        }
        private List<Dev_DictionaryField> dev_DictionaryFields = null;
        public List<Dev_DictionaryField> Dev_DictionaryFields
        {
            get
            {
                if (dev_DictionaryFields == null)
                {
                    EasyManufactureEntities entities = LegacyDbFactory.CreateEntities();

                    dev_DictionaryFields = entities.Dev_DictionaryField.Where(m => m.DictionaryID == DictionaryID&&m.IsSelect==true ).OrderByDescending(m => m.IsFrozen).ToList();
                }

                return dev_DictionaryFields;
            }
        }
        private int footRows = 0;
        private List<string> listFoot = new List<string>();
        /// <summary>
        /// 缓存数据源表
        /// </summary>
        public Dictionary<String, List<DataTable>> DicDataSource { get; } = new Dictionary<string, List<DataTable>>();
        V_Dev_Account dev_Account = V_Dev_Account.GetDev_Account();
        /// <summary>
        /// 最后拼接的条件
        /// </summary>
        public string ResultWhere
        {
            get; set;
        }
        public string Fields
        {
            get;set;

        }
        /// <summary>
        /// 分组
        /// </summary>
        public string GroupBy
        {
            get;set;
        }
        /// <summary>
        /// 生成SQL语句
        /// </summary>
        /// <param name="operationType">操作方式</param>
        /// <param name="fields">字段集合</param>
        /// <param name="prefix">前缀，有这个值则表示要过滤客户端键值对参数命</param>
        /// <param name="listExclude">需要排除的字段</param>
        public void GetSql(OperationType operationType, string fields = "", string prefix = "", List<string> listExclude = null, string insertKeyValue = "")
        {
            if (listExclude == null)
            {
                listExclude = new List<string>();
            }

            Entitys.Dev_Button dev_Button = new Dev_Button();

            if (!string.IsNullOrEmpty(prefix))
            {
                Prefix = prefix;
            }
            SqlParameters = new SqlParameter[SqlParameters.Length];
            V_Dev_Account dev_Account = V_Dev_Account.GetDev_Account();
            if (dev_Account == null)
            {
                if (!string.IsNullOrEmpty(Account))
                {
                    dev_Account = LegacyDbFactory.CreateEntities().V_Dev_Account.Where(m => m.Account == Account).FirstOrDefault();
                }
                else
                {
                    dev_Account = new V_Dev_Account();
                }
            }
            string parameter = "";

            if (!string.IsNullOrEmpty(Where))
            {
                ResultWhere = Where;
            }


            int pageSize = 200;
            int pageIndex = 1;
            if (NameValueCollection != null)
            {
                int.TryParse(NameValueCollection["rows"], out pageSize);
                int.TryParse(NameValueCollection["page"], out pageIndex);
            }
            string dataFilter = "";
            if(JsToken!=null)
            {
                try
                {
                    if(JsToken["rows"]!=null)
                    {
                        int.TryParse(JsToken["rows"].ToString(), out pageSize);
                    }
                    if(JsToken["page"]!=null)
                    {
                        int.TryParse(JsToken["page"].ToString(), out pageIndex);
                    }
                    if (JsToken["DataFilter"] != null&&dev_Account!=null)
                    {
                        dataFilter = JsToken["DataFilter"].ToString();
                    }
                    if (!string.IsNullOrEmpty(LicenceRuntime.Http.HttpContext.Request.Headers["UserLanguage"].ToString()))
                    {
                        if (JsToken.Contains("RegionCode") == false) {
                            JsToken["RegionCode"] = LicenceRuntime.Http.HttpContext.Request.Headers["UserLanguage"].ToString();
                        }
                    }
                }
                catch(Exception ex)
                { }

            }
            if (PageSize > 0)
            {
                pageIndex = PageIndex;
                pageSize = PageSize;
            }
            if (PageSize == 0)
            {
                PageSize = pageSize;
            }
            DataTable dtTableInfo = null;
            if (DicDataSource.ContainsKey(TabelName) == false)
            {
                dtTableInfo = GetFieldByTableName(TabelName);
                List<DataTable> dataTables = new List<DataTable>();
                dataTables.Add(dtTableInfo);
                DicDataSource.Add(TabelName, dataTables);
            }
            else
            {
                dtTableInfo = DicDataSource[TabelName][0];
            }

            if (OperationType.Insert == operationType)
            {//目前发现这个值有问题，需要纠正

                foreach (DataRow dr in DtDictionary.Rows)
                {
                    bool isKey = dr["IsKey"].ToString().ToLower() == "true";
                    bool isIdentity = dr["IsIdentity"].ToString().ToLower() == "true";
                    if (isKey)
                    {
                        string value = "";
                        string parameterName = dr["ParameterName"].ToString();
                        if (NameValueCollection != null)
                        {
                            value = NameValueCollection[Prefix + parameterName];

                        }
                        else if (JsToken != null && JsToken[parameterName] != null)
                        {
                            value = JsToken[parameterName].ToString();
                        }
                        if (CustomerNameValue.ContainsKey(parameterName))
                        {//优先客户自定义值
                            value = CustomerNameValue[parameterName];
                        }
                        if (!string.IsNullOrEmpty(value) && value.IndexOf("temp") == -1)
                        {
                            string sqlTemp = "SELECT top 1 1 FROM " + TabelName + "(NOLOCK) WHERE " + parameterName + "='" + value.Replace("'", "'") + "'";
                            DataTable dataTable = SqlHelper.ExecuteDataTable(sqlTemp);
                            if (dataTable.Rows.Count > 0)
                            {
                                operationType = OperationType.Update;
                            }

                        }

                        break;
                    }
                }
            }
            if (OperationType.Update == operationType)
            {//目前发现这个值有问题，需要纠正
                foreach (DataRow dr in DtDictionary.Rows)
                {
                    bool isKey = dr["IsKey"].ToString().ToLower() == "true";
                    bool isIdentity = dr["IsIdentity"].ToString().ToLower() == "true";
                    if (isKey)
                    {
                        string value = "";
                        string parameterName = dr["ParameterName"].ToString();
                        if (NameValueCollection != null)
                        {
                            value = NameValueCollection[Prefix + parameterName];
                            keyValue = value;
                        }
                        else if (JsToken != null && JsToken[parameterName] != null)
                        {
                            value = JsToken[parameterName].ToString();
                            keyValue = value;
                        }
                        if (CustomerNameValue.ContainsKey(parameterName))
                        {//优先客户自定义值
                            value = CustomerNameValue[parameterName];
                            keyValue = value;
                        }
                        if (string.IsNullOrEmpty(value))
                        {
                            operationType = OperationType.Insert;

                        }

                        break;
                    }
                }

            }
            if (!string.IsNullOrEmpty(Fields))
            {
                fields = Fields;
            }
            else
            {
                if (IsQueryVisible == true && operationType == OperationType.Select)
                {
                    foreach (var tmp in this.Dev_DictionaryFields)
                    {
                        if (tmp.IsKey == true || tmp.IsVisible == true||tmp.IsEdit==true||tmp.IsQuery==true||tmp.FieldLength<500)
                        {
                            fields += tmp.ParameterName + ",";
                        }
                    }
                    fields = fields.Trim(',');
                }
            }
            switch (operationType)
            {

                case OperationType.Select:
                  
                    this.ResultWhere += Condition;
                    if(string.IsNullOrEmpty(fields))
                    {

                        foreach (var dic in Dev_DictionaryFields.OrderByDescending(m => m.IsVisible.GetValueOrDefault(false)).ThenBy(m => m.FieldIndex).ThenBy(m => m.ParameterName))
                        {
                            fields += dic.ParameterName + ",";
                        }
                        fields = fields.Trim(',');
                    }
                    sql = " " + (string.IsNullOrEmpty(fields) ? "*" : fields) + " FROM " + ObjectName + "(nolock) WHERE   "+(IsUserOR?"1 = 2 ":"1 = 1 ")+ dataFilter;
                    break;

                case OperationType.Insert:
                    sql = "INSERT INTO " + TabelName + "(";
                    parameter = ") VALUES(";

                    break;
                case OperationType.Update:
                    sql = "UPDATE " + TabelName + " SET ";
                    break;
                case OperationType.Delete:
                    sql = "DELETE " + TabelName + "   ";
                    break;
            }
            int rowIndex = 0;


            string orderBy = "";
            if (!string.IsNullOrEmpty(OrderBy))
            {
                orderBy = OrderBy;
            }
            // 多值查询保序表达式（最终 ORDER BY：输入顺序 → 原有 SortType/前端 sort）
            var searchOrderExprs = new List<string>();
            string keyField = "";
            //组织条件
            string organizeIDCondition = "";
            string footSql = "";


            JArray jArrayQueryParams = null;
            bool isQueryType = false;
            if (JsToken != null && JsToken["QueryParams"]!=null)
            {
                jArrayQueryParams = JsToken["QueryParams"] as JArray;
                
            }
            foreach (DataRow dr in DtDictionary.Rows)
            {
                //底部求和等等

                string footerType = dr["FooterType"].ToString();

                string parameterName = dr["ParameterName"].ToString();
                if (listExclude.Contains(parameterName.ToLower()))
                {
                    continue;
                }
                if (!string.IsNullOrEmpty(footerType))
                {
                    string[] footerTypes = footerType.Split(',');
                    if (footRows < footerTypes.Length)
                    {
                        footRows = footerTypes.Length;
                    }
                    foreach (string f in footerTypes)
                    {
                        if (!string.IsNullOrEmpty(f))
                        {
                            if (listFoot.Contains(f) == false)
                            {
                                listFoot.Add(f);
                            }
                            footSql += f + "(" + parameterName + ") AS " + f + parameterName + ",";
                        }

                    }
                }
                int tmp = 0;
                int.TryParse(dr["queryMethod"].ToString(), out tmp);
                QueryMethod queryMethod = (QueryMethod)Enum.Parse(typeof(QueryMethod), tmp.ToString());
                bool isKey = dr["IsKey"].ToString().ToLower() == "true";
                bool isIdentity = dr["IsIdentity"].ToString().ToLower() == "true";
                if (isKey)
                {

                    keyField = parameterName;
                }
                if (AppInfo.IsMultiOrganization)
                {

                    if (dev_Account.Account.ToLower() != "admin")
                    {
                        //有组织则判断组织
                        if (parameterName.ToLower() == "MFGOrganizeID".ToLower())
                        {
                            organizeIDCondition = " and MFGOrganizeID=" + dev_Account.CenterID;
                        }
                        else if (parameterName.ToLower() == "OrganizeIDs".ToLower())
                        {//包含组织级别
                            organizeIDCondition = "  and OrganizeIDs like '%$" + dev_Account.GroupID + "$%'";
                        }
                        else if (parameterName.ToLower() == "OrganizeID".ToLower() && string.IsNullOrEmpty(organizeIDCondition))
                        {
                            organizeIDCondition = " and  (OrganizeID is null or OrganizeID=" + dev_Account.CenterID + ")";
                        }

                    }

                }
                bool isDbNull = IsDbNull(parameterName, dr["DataType"].ToString());


                string searchParameterName = parameterName;
                if (NameValueCollection != null && operationType == OperationType.Select)
                {


                    foreach (string s in NameValueCollection.Keys)
                    {
                        if (Prefix + searchParameterName + "[]" == s)
                        {
                            searchParameterName = searchParameterName + "[]";
                            if (string.IsNullOrEmpty(dr["queryMethod"].ToString()))
                                queryMethod = QueryMethod.范围;

                        }
                    }
                  
                }
                if(string.IsNullOrEmpty(GroupBy))
                {
                    if (!string.IsNullOrEmpty(dr["SortType"].ToString()))
                    {
                        if (!string.IsNullOrEmpty(orderBy))
                        {
                            orderBy = orderBy.Trim(',') + "," + parameterName + " " + dr["SortType"].ToString() + ",";
                        }
                        else
                        {
                            orderBy = parameterName + " " + dr["SortType"].ToString() + ",";
                        }

                    }
                }

                if ((NameValueCollection != null && NameValueCollection[Prefix + searchParameterName] != null) || (JsToken != null && JsToken[parameterName] != null) || ListSystemField.Contains(parameterName) || CustomerNameValue.ContainsKey(parameterName) || (operationType == OperationType.Insert)||!string.IsNullOrEmpty(LicenceRuntime.Http.HttpContext.Request.GetRequestValue(Prefix + searchParameterName))|| jArrayQueryParams!=null)
                {
                    bool isArray = false;
                    string value = LicenceRuntime.Http.HttpContext.Request.GetRequestValue(Prefix + searchParameterName);
                    if (NameValueCollection != null&& string.IsNullOrEmpty(value))
                    {
                        value = NameValueCollection[Prefix + searchParameterName];

                    }
                    else if (JsToken != null && JsToken[parameterName] != null)
                    {
                        var token = JsToken[parameterName];
                        if (token is JArray arr)
                        {
                            isArray = arr.Count > 0;
                            value = string.Join(",", arr
                                .Where(t => t != null && t.Type != JTokenType.Null)
                                .Select(t => t.ToString()));
                        }
                        else if (token is JValue jv && jv.Value != null)
                        {
                            value = jv.Value.ToString() ?? string.Empty;
                            if (value.TrimStart().StartsWith('['))
                            {
                                try
                                {
                                    if (JToken.Parse(value) is JArray parsed && parsed.Count > 0)
                                    {
                                        isArray = true;
                                        value = string.Join(",", parsed.Select(t => t.ToString()));
                                    }
                                }
                                catch
                                {
                                    // 与旧版一致：解析失败时沿用原始字符串
                                }
                            }
                        }
                        else
                        {
                            value = string.Empty;
                            foreach (var obj in token)
                            {
                                value += obj.ToString() + ",";
                                isArray = true;
                            }
                        }
                    }
                    if(jArrayQueryParams!=null)
                    {
                        foreach (JObject obj in jArrayQueryParams)
                        {
                            if(obj.ContainsKey(parameterName))
                            {
                                var qpToken = obj[parameterName];
                                if (qpToken is JArray qpArr)
                                    value = string.Join(",", qpArr.Select(t => t.ToString()));
                                else
                                    value = qpToken?.ToString() ?? string.Empty;
                               string   queryType = obj["queryTypeValue"].ToString();
                                if (!string.IsNullOrEmpty(queryType))
                                {
                                    queryMethod = (QueryMethod)Enum.Parse(typeof(QueryMethod), queryType);
                                    isQueryType = true;
                                }
                             
                            }
                        }
                    }
                    if (CustomerNameValue.ContainsKey(parameterName))
                    {//优先客户自定义值
                        value = CustomerNameValue[parameterName];
                    }
                    if (operationType == OperationType.Insert && (isKey && (string.IsNullOrEmpty(value) || value.IndexOf("temp") > -1) && isIdentity == false))
                    {
                        if (string.IsNullOrEmpty(insertKeyValue))
                        {
                            value = SqlHelper.GetKeyValue(TabelName, parameterName, AppInfo.AppCode);
                        }
                        else
                        {
                            value = insertKeyValue;
                        }

                        keyValue = value;

                    }
                    if (!string.IsNullOrEmpty(value))
                    {
                        value = value.Trim();
                    }
                    if(isKey&&!string.IsNullOrEmpty(value))
                    {
                        keyValue = value;
                    }

                    if (operationType == OperationType.Insert || operationType == OperationType.Update)
                    {//插入或更新，查本表数据

                        DataRow[] drTable = dtTableInfo.Select("ParameterName='" + parameterName + "'");
                        if (drTable.Length == 0)
                        {//本数据表不存在

                            if (isDbNull == true && string.IsNullOrEmpty(value))
                            {

                                SqlParameters[rowIndex] = new SqlParameter("@" + parameterName, DBNull.Value);
                            }
                            else
                            {
                                SqlParameters[rowIndex] = new SqlParameter("@" + parameterName, value);
                            }

                            rowIndex++;
                            continue;
                        }
                        isKey = drTable[0]["IsKey"].ToString().ToLower() == "true";
                        isIdentity = drTable[0]["IsIdentity"].ToString().ToLower() == "true";

                        if (operationType == OperationType.Insert && isIdentity)
                        {
                            //插入的时候跳出
                            continue;
                        }
                        if (operationType == OperationType.Insert && string.IsNullOrEmpty(value) && !string.IsNullOrEmpty(dr["DefaultAddValue"].ToString()))
                        {//**********临时屏蔽的代码***************8
                            value = StringHelper.GetDefaultValue(this.TabelName, dr["DefaultAddValue"].ToString(), parameterName, false).ToString();
                        }
                    }
                    if (!string.IsNullOrEmpty(value))
                    {
                        var controlType = dr["ControlType"].ToString().ToLower();
                        if (controlType == "el-date-picker" || controlType == "datebox")
                            value = NormalizeDateRangeQueryValue(value);
                    }
                        switch (operationType)
                    {

                        case OperationType.Select:

                            if (!string.IsNullOrEmpty(value))
                            {
                               
                                string[] values = value.Split(',');

                                if (isQueryType == false)
                                {


                                    if (values.Length >= 1 && (dr["ControlType"].ToString().ToLower() == "datebox" || dr["ControlType"].ToString().ToLower() == "el-date-picker") && string.IsNullOrEmpty(dr["queryMethod"].ToString()))
                                    {

                                        queryMethod = QueryMethod.范围;
                                    }
                                    //if (dr["queryMethod"].ToString() == "")
                                    if (queryMethod == QueryMethod.模糊匹配)
                                    {
                                        if (dr["DataType"].ToString().ToLower() == "bigint" || dr["DataType"].ToString().ToLower() == "int")
                                        {
                                            queryMethod = QueryMethod.精确匹配;
                                        }
                                    }

                                    if (values.Length >= 2 && dr["ControlType"].ToString().ToLower() == "datebox")
                                    {
                                        value = values[0];
                                        if (dr["ControlType"].ToString().ToLower() == "datebox")
                                        {
                                            value = "'" + value + "'";
                                        }
                                    }

                                    else if (dr["ControlType"].ToString().ToLower() == "datebox" && queryMethod == QueryMethod.模糊匹配)
                                    {//日期只有一个，则是结束日期
                                        queryMethod = QueryMethod.小于等于;
                                        value = "'" + value + "'";
                                    }

                                    if (dr["DataType"].ToString().ToLower() == "bit" && !string.IsNullOrEmpty(value))
                                    {
                                        queryMethod = QueryMethod.精确匹配;
                                    }
                                }
                                // 支持逗号 / 中文逗号 / 换行 / Tab 多值粘贴，并按粘贴顺序保序
                                string[] matchCollection;
                                if (dr["DataType"].ToString().ToLower() == "datetime" || dr["DataType"].ToString().ToLower() == "date")
                                {
                                    matchCollection = value.Split(',');
                                }
                                else
                                {
                                    string splitSrc = value
                                        .Replace('，', ',')
                                        .Replace("\r\n", ",")
                                        .Replace('\r', ',')
                                        .Replace('\n', ',')
                                        .Replace('\t', ',');
                                    matchCollection = splitSrc.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                                    if (matchCollection.Length > 1)
                                    {
                                        isArray = true;
                                    }
                                }
                                string valueIn = "";
                                string whereLike = "(";
                                // 多值保序：用 VALUES(序号,值) 替代 CHARINDEX（避免前缀误匹配，且 int 也可用）
                                string orderByValues = "";
                                int orderSeq = 0;
                                bool isNumericKey = dr["DataType"].ToString().ToLower() == "bigint"
                                    || dr["DataType"].ToString().ToLower() == "int";
                                if (isArray)
                                {
                                    foreach (string v in matchCollection)
                                    {
                                        string  v1 = v.Trim().Replace("'","''");
                                        if (!string.IsNullOrEmpty(v1))
                                        {
                                            orderSeq++;
                                            if (isNumericKey)
                                            {
                                              //  if(queryMethod!= QueryMethod.模糊匹配)
                                                {
                                                    queryMethod = QueryMethod.IN;
                                                }
                                         
                                                valueIn += "" + v1.Replace("'", "") + ",";
                                                orderByValues += "(" + orderSeq + "," + v1.Replace("'", "") + "),";
                                            }
                                            else
                                            {
                                                valueIn += "'" + v1.Replace("'", "") + "',";
                                                orderByValues += "(" + orderSeq + ",N'" + v1 + "'),";
                                                if(v.EndsWith("*"))
                                                {
                                                    v1 = " LIKE '" + v.TrimEnd('*') + "%'";
                                                }
                                                else if (v.StartsWith("*"))
                                                {
                                                    v1 = " LIKE '%" + v.TrimStart('*') + "'";
                                                }
                                                else
                                                {
                                                    v1 = " LIKE '%" + v.TrimStart('*') + "%'";
                                                }
                                                if(whereLike!="(")
                                                {
                                                     
                                                    if(queryMethod==QueryMethod.多个值与)
                                                    {
                                                        whereLike += " AND " + parameterName + v1;
                                                    }
                                                    else
                                                    {
                                                        whereLike += " OR " + parameterName + v1;
                                                    }
                                                   
                                                }
                                                 else
                                                {
                                                    whereLike += parameterName + v1;
                                                }
                                            }
                                        }
                                        else
                                        {
                                           // valueIn += "'',";
                                        }

                                    }
                                    whereLike += ")";
                                }
                                if (matchCollection.Length > 1&&!string.IsNullOrEmpty(valueIn)&&queryMethod!= QueryMethod.NOTIN&&queryMethod!= QueryMethod.范围)
                                {
                                    if(queryMethod== QueryMethod.模糊匹配|| queryMethod == QueryMethod.多个值与)
                                    {
                                        
                                        if ((DictionaryID == 7850 || DictionaryID == 7862) && parameterName.ToLower() == "POSuplierName".ToLower())
                                        {//EK查供应商
                                            ResultWhere += " AND "  +parameterName + " LIKE '%," + value.Replace("'", "''") + ",%'";
                                        }
                                        else
                                        {
                                            ResultWhere += " AND " + whereLike;
                                        }
                                    }
                                    else
                                    {
                                        ResultWhere += " AND  " + parameterName + " IN (" + valueIn.Trim(',') + ")";
                                    }

                                    // 先记下输入顺序；最终与字典 SortType / 前端 sort 拼接时再放到最前
                                    if (!string.IsNullOrEmpty(orderByValues))
                                    {
                                        string orderExpr = "ISNULL((SELECT TOP 1 Seq FROM (VALUES "
                                            + orderByValues.TrimEnd(',')
                                            + ") AS _apsOrd(Seq,Val) WHERE _apsOrd.Val=" + parameterName
                                            + "),2147483647)";
                                        searchOrderExprs.Add(orderExpr);
                                    }
                                 
                               
                                }
                                else
                                {

                                    string tmpstr = " AND ";
                                    if(IsUserOR)
                                    {
                                        tmpstr = " OR ";
                                    }
                                    switch (queryMethod)
                                    {
                                        default:
                                        case QueryMethod.模糊匹配:
                                           if(value== "null")
                                            {
                                                value = "";
                                            }
                                            if(value.StartsWith("<>"))
                                            {
                                                ResultWhere += tmpstr + parameterName + "" + value.Replace("'", "''") + "";
                                            }
                                            else
                                            {
                                                if(parameterName.ToLower()== "OrganizeIDs".ToLower())
                                                {
                                                    ResultWhere += tmpstr + parameterName + " LIKE '%$" + value.Replace("'", "''") + "$%'";
                                                }
                                                else
                                                {
                                                    if((DictionaryID==7850||DictionaryID==7862)&& parameterName.ToLower()== "POSuplierName".ToLower())
                                                    {//EK查供应商
                                                        ResultWhere += tmpstr + parameterName + " LIKE '%," + value.Replace("'", "''") + ",%'";
                                                    }
                                                    else
                                                    {
                                                        value = value.Replace("'", "''");
                                                        if (value.EndsWith("*"))
                                                        {
                                                            value = " LIKE '" + value.TrimEnd('*') + "%'";
                                                        }
                                                        else if (value.StartsWith("*"))
                                                        {
                                                            value = " LIKE '%" + value.TrimStart('*') + "'";
                                                        }
                                                        else
                                                        {
                                                            value = " LIKE '%" + value + "%'";
                                                        }
                                                        ResultWhere += tmpstr + parameterName + value;
                                                    }
                                                   
                                                }
                                              
                                            }
                                            break;
                                        case QueryMethod.包含逗号:
                                            ResultWhere += tmpstr + parameterName + " LIKE '%," + value.Replace("'", "''") + ",%'";
                                            break;
                                        case QueryMethod.右匹配:
                                            ResultWhere += tmpstr + parameterName + " LIKE '%" + value.Replace("'", "''") + "'";
                                            break;
                                        case QueryMethod.大于:
                                            if ((dr["ControlType"].ToString().ToLower() == "datebox" || dr["ControlType"].ToString().ToLower() == "el-date-picker"))
                                            {
                                                ResultWhere += tmpstr + parameterName + ">'" + value + "'";
                                            }
                                            else
                                            {
                                                ResultWhere += tmpstr + parameterName + ">" + value;
                                            }
                                            break;
                                        case QueryMethod.大于等于:
                                            if ((dr["ControlType"].ToString().ToLower() == "datebox" || dr["ControlType"].ToString().ToLower() == "el-date-picker"))
                                            {
                                                ResultWhere += tmpstr + parameterName + ">='" + value + "'";
                                            }
                                            else
                                            {
                                                ResultWhere += tmpstr + parameterName + ">=" + value;
                                            }
                                            break;
                                        case QueryMethod.小于:
                                            if((dr["ControlType"].ToString().ToLower() == "datebox" || dr["ControlType"].ToString().ToLower() == "el-date-picker"))
                                            {
                                                ResultWhere += tmpstr + parameterName + "<'" + value+"'";
                                            }
                                            else
                                            {
                                                ResultWhere += tmpstr + parameterName + "<" + value;
                                            }
                                           
                                            break;
                                        case QueryMethod.小于等于:
                                            if ((dr["ControlType"].ToString().ToLower() == "datebox" || dr["ControlType"].ToString().ToLower() == "el-date-picker"))
                                            {
                                                ResultWhere += tmpstr + parameterName + "<='" + value + "'";
                                            }
                                            else
                                            {
                                                ResultWhere += tmpstr + parameterName + "<=" + value;
                                            }
                                            break;
                                        case QueryMethod.左匹配:
                                            ResultWhere += tmpstr + parameterName + " LIKE '" + value.Replace("'", "") + "%'";
                                            break;
                                        case QueryMethod.精确匹配:
                                            ResultWhere += tmpstr + parameterName + "='" + value.Replace("'", "") + "'";
                                            break;
                                        case QueryMethod.IN:
                                            ResultWhere += tmpstr + parameterName + " IN(" + value.Trim(',') + ")";
                                            break;
                                        case QueryMethod.NOTIN:
                                            ResultWhere += tmpstr + parameterName + " NOT IN(" + value.Trim(',') + ")";
                                            break;
                                        case QueryMethod.Null:

                                            if (string.IsNullOrEmpty(value))
                                            {
                                                //where += " AND  (" + parameterName + " IS NULL OR )";
                                            }
                                            else
                                            {
                                                if (value == "null")
                                                {
                                                    ResultWhere += tmpstr + "ISNULL("+parameterName + ",'')=''";
                                                }
                                                else
                                                {
                                                    ResultWhere += tmpstr + "ISNULL(" + parameterName + ",'')<>''";
                                                }

                                            }
                                            break;
                                        case QueryMethod.大于0:
                                            if (string.IsNullOrEmpty(value))
                                            {
                                                //where += " AND  (" + parameterName + " IS NULL OR )";
                                            }
                                            else
                                            {
                                                if (value == "0")
                                                {
                                                    ResultWhere += tmpstr + "ISNULL(" + parameterName + ",0)<=0";
                                                }
                                                else
                                                {
                                                    ResultWhere += tmpstr + "ISNULL(" + parameterName + ",0)>0";
                                                }

                                            }

                                            break;
                                        case QueryMethod.范围:

                                            if (!string.IsNullOrEmpty(values[0]))
                                            {
                                                ResultWhere += " AND " + parameterName + ">='" + values[0] + "'";
                                            }
                                            if (values.Length > 1 && !string.IsNullOrEmpty(values[1]))
                                            {
                                                if (dr["ControlType"].ToString().ToLower() == "datebox"|| dr["ControlType"].ToString().ToLower() == "el-date-picker")
                                                {
                                                    ResultWhere += "  AND " + parameterName + "<'" + DateTime.Parse(values[1]).AddDays(1) + "'";
                                                }
                                                else
                                                {
                                                    ResultWhere += "  AND " + parameterName + "<='" + values[1] + "'";
                                                }

                                            }
                                            else if(values.Length==1)
                                            {
                                                if (dr["ControlType"].ToString().ToLower() == "datebox" || dr["ControlType"].ToString().ToLower() == "el-date-picker")
                                                {
                                                    ResultWhere += "  AND " + parameterName + "<'" + DateTime.Parse(values[0]).AddDays(1) + "'";
                                                }
                                            }

                                            break;

                                    }
                                }
                             
                            }
                            else
                            {
                                continue;
                            }

                            break;
                        case OperationType.Delete:
                            if (isKey)
                            {
                                ResultWhere += " AND " + parameterName + "=@" + parameterName;
                            }
                            break;
                        case OperationType.Update:
                            if (parameterName.ToLower() == "modifyedon")
                            {
                                value = DateTime.Now.ToString();
                            }
                            if (parameterName.ToLower() == "modifiedby")
                            {
                                value = dev_Account.Account;
                            }
                            if (parameterName.ToLower() == "modifiedbyname")
                            {
                                value = dev_Account.Name;
                            }
                            if (parameterName.ToLower() == "createdon" || parameterName.ToLower() == "createdby" || parameterName.ToLower() == "createdbyname")
                            {
                                continue;
                            }
                            if (isKey)
                            {
                                ResultWhere += " AND " + parameterName + "=@" + parameterName;
                            }
                            else
                            {

                                sql += parameterName + "=@" + parameterName + ",";
                            }
                         
                            break;
                        case OperationType.Insert:

                            if (parameterName.ToLower() == "modifyedon")
                            {
                                value = DateTime.Now.ToString();
                            }
                            if (parameterName.ToLower() == "modifiedby")
                            {
                                value = dev_Account.Account;
                            }
                            if (parameterName.ToLower() == "modifiedbyname")
                            {
                                value = dev_Account.Name;
                            }

                            if (parameterName.ToLower() == "createdon" || parameterName.ToLower() == "modifyedon")
                            {
                                value = DateTime.Now.ToString();
                            }
                            else if (parameterName.ToLower() == "createdby")
                            {
                                value = dev_Account.Account;
                            }
                            else if (parameterName.ToLower() == "status" && string.IsNullOrEmpty(value))
                            {
                                value = "1";
                            }
                            else if (parameterName.ToLower() == "createdbyname")
                            {
                                value = dev_Account.Name;
                            }
                            else if (parameterName.ToLower() == "OrganizeID".ToLower() && string.IsNullOrEmpty(value))
                            {
                                value = dev_Account.CenterID.ToString();
                            }
                            else if (isIdentity||string.IsNullOrEmpty(value))
                            {

                                continue;
                            }
                            if (dr["DefaultValue"].ToString().StartsWith("(") && dr["DefaultValue"].ToString().EndsWith(")"))
                            {
                                parameter += "" + dr["DefaultValue"].ToString() + ",";
                            }
                            else
                            {
                                parameter += "@" + parameterName + ",";
                            }
                            sql += parameterName + ",";

                            break;


                    }
                
                    
                    if (isDbNull == true && string.IsNullOrEmpty(value))
                    {
                        SqlParameters[rowIndex] = new SqlParameter("@" + parameterName, DBNull.Value);
                    }
                    else
                    {
                        SqlParameters[rowIndex] = new SqlParameter("@" + parameterName, value);
                    }

                    rowIndex++;
                }


            }

            //客户端排序
            string? sort = LicenceRuntime.Http.HttpContext?.Request.GetRequestValue("sort");
            string? order = LicenceRuntime.Http.HttpContext?.Request.GetRequestValue("order");

            if (JsToken != null)
            {
                try
                {
                    if (JsToken["sort"] != null && JsToken["sort"].ToString().Trim().EndsWith("null") == false)
                    {
                        sort = JsToken["sort"].ToString();

                        sort = sort.Replace("ending", "");
                    }

                }
                catch (Exception ex)
                { }

            }
            if (!string.IsNullOrEmpty(sort))
            {
                // 有多值输入保序时：前端列排序只能接在后面，不能整段覆盖
                bool hasSearchOrder = searchOrderExprs.Count > 0;
                string sortField = sort.Split(' ')[0];
                if (hasSearchOrder)
                {
                    if (orderBy.IndexOf(sortField, StringComparison.OrdinalIgnoreCase) < 0)
                    {
                        orderBy = orderBy.Trim(',') + "," + sort + " " + (order ?? "");
                    }
                }
                else if (orderBy.ToLower().IndexOf(sortField.ToLower()) == -1)
                {
                    orderBy = sort + " " + order + (string.IsNullOrEmpty(orderBy) || orderBy == sort ? "" : "," + orderBy);
                }
                else
                {
                    orderBy = sort;
                }

            }
            if (string.IsNullOrEmpty(orderBy))
            {
                orderBy = keyField;
            }
            //else
            //{

            //    orderBy = orderBy.Trim(',')+ "," +keyField;
            //}
            orderBy = orderBy.Trim(',');
            // 最终顺序：输入顺序 → 原有排序（字典 SortType / 前端 sort / 主键）
            if (searchOrderExprs.Count > 0)
            {
                string searchOrd = string.Join(",", searchOrderExprs);
                orderBy = string.IsNullOrEmpty(orderBy) ? searchOrd : (searchOrd + "," + orderBy);
            }
            int start = (pageIndex - 1) * pageSize;
            int end = start + pageSize - 1;
            if (operationType == OperationType.Select)
            {
                ResultWhere += organizeIDCondition;
            }


            switch (operationType)
            {

                case OperationType.Select:

                    #region 判定是否启用控制者
                    if(AppInfo.IsControlID&& dev_Account!=null&&  Dev_DictionaryFields.Where(m=>m.ParameterName== "ControlID").Count()==1&&this.TabelName.ToLower()!= "APS_OrderControl".ToLower())
                    {
                        string controlIDSQL = @"
                          SELECT [ControlID] 
                          FROM [dbo].[APS_OrderControl]
                          WHERE [Status]=1 and Account='" + dev_Account.Account + @"'
                             UNION ALL
                          SELECT [ControlID] 
                          FROM [dbo].[APS_OrderControl] A
						  INNER JOIN Dev_Organize B ON A.OrganizeID=B.OrganizeID
                          WHERE A.[Status]=1 and OrganizeIDs LIKE '%$" + dev_Account.CenterID + @"$%'
                                


                            ";


                        DataTable dataTable = SqlHelper.ExecuteDataTable(controlIDSQL);
                        if(dataTable.Rows.Count>0)
                        {

                            ResultWhere += @" AND ControlID IN("+ controlIDSQL + ")";
                        }
                    }

                    #endregion



                    if (string.IsNullOrEmpty(Fields))
                    {//指定字段
                        if(dev_DictionaryFields.Where(m=>m.ParameterName== "isChecked").Count()==0)
                        {
                            sql = @"SELECT ROW_NUMBER() OVER (ORDER BY {0}) AS 'RowNumber',CAST('false' as bit) as isChecked," + sql + ResultWhere + @"
ORDER BY {0} " + (pageSize > 0 ? @"OFFSET {1}
                    ROW FETCH NEXT " + pageSize + @" ROW ONLY
" : "");
                        }
          else
                        {
                            sql = @"SELECT ROW_NUMBER() OVER (ORDER BY {0}) AS 'RowNumber'," + sql + ResultWhere + @"
ORDER BY {0} " + (pageSize > 0 ? @"OFFSET {1}
                    ROW FETCH NEXT " + pageSize + @" ROW ONLY
" : "");
                        }
                        SQLOfCount = @"
                            ;SELECT COUNT(1) AS RecordCount from " + ObjectName + "(NOLOCK) WHERE  " + (IsUserOR ? "1=2 " : "1=1") + ResultWhere;
                    }
                   else
                    {
                        if (!string.IsNullOrEmpty(GroupBy))
                        {
                            // orderBy = fields.Substring(0, fields.IndexOf(','));
                            //分组查询需要独立计算记录数
                            SQLOfCount = @"
                            ;SELECT COUNT(1) AS RecordCount from " + "(SELECT " + sql + this.ResultWhere + " GROUP BY " + this.GroupBy + ") A ";
                            sql = "SELECT " + (this.PageSize > 0 ? " TOP " + this.PageSize.ToString() : "") + sql + this.ResultWhere + " GROUP BY " + this.GroupBy + (string.IsNullOrEmpty(orderBy) ? "" : " ORDER BY " + orderBy);

                        }
                        else
                        {
                           sql = "SELECT " +  sql + this.ResultWhere;
                            SQLOfCount = @"
                            ;SELECT COUNT(1) AS RecordCount from " + ObjectName + "(NOLOCK) WHERE  " + (IsUserOR ? "1=2 " : "1=1") + ResultWhere;
                        }

                    }
             

                    SQLOfSelect = sql;
                    
                
                    sql += SQLOfCount;
                    if (!string.IsNullOrEmpty(footSql))
                    {
                        sql += ";SELECT " + footSql.Trim(',') + " FROM " + ObjectName + "(nolock) WHERE " + (IsUserOR ? "1=2 " : "1=1") + ResultWhere;
                    }

                    break;
                case OperationType.Delete:
                case OperationType.Update:
                    sql = sql.Trim(',') + " WHERE 1=1   " + (string.IsNullOrEmpty(ResultWhere) ? " and 1=2" : ResultWhere);
                    break;
                case OperationType.Insert:
                    if (!string.IsNullOrEmpty(parameter))
                    {
                        parameter = parameter.Trim(',') + ")";
                    }
                    sql = sql.Trim(',') + parameter;

                    break;
            }
          

            SystemLog systemLog2 = new SystemLog();
            if (operationType == OperationType.Select)
            {//查询强制默认一个排序
                if (string.IsNullOrEmpty(orderBy) && this.Dev_DictionaryFields.Where(m => m.ParameterName.ToLower() == "createdon").Count() == 0)
                {//没有查询，并且没有创建日期，默认第一个排序
                    orderBy = this.Dev_DictionaryFields[0].ParameterName;
                }

                //if (this.Dev_DictionaryFields.Where(m => m.ParameterName.ToLower() == "createdon").Count()==1)
                {
                    sql = string.Format(sql.Trim(','), string.IsNullOrEmpty(orderBy) ? "createdon desc" : orderBy, start);
                    SQLOfSelect = string.Format(SQLOfSelect.Trim(','), string.IsNullOrEmpty(orderBy) ? "createdon desc" : orderBy, start);

                }

            }
            else if (operationType == OperationType.Update)
            {

                sql = sql.Trim(',');


                if (!string.IsNullOrEmpty(BeforeUpdate))
                {
                    sql = BeforeUpdate + ";" + sql;
                }
                if (!string.IsNullOrEmpty(AfterUpdate))
                {
                    sql += ";" + AfterUpdate;
                }
                // systemLog2.SaveLog(SystemLog.SystemLogType.SQL更新, sql);                                                                           
            }
            else if (operationType == OperationType.Insert)
            {

                sql = sql.Trim(',');
                if (!string.IsNullOrEmpty(AfterAdd))
                {
                    sql += ";" + AfterAdd;
                }
                if (!string.IsNullOrEmpty(AfterUpdate))
                {
                    // sql += ";" + AfterUpdate;
                }
                // systemLog2.SaveLog(SystemLog.SystemLogType.SQL添加, sql);
            }
            else if (operationType == OperationType.Delete)
            {

                sql = sql.Trim(',');
                if (!string.IsNullOrEmpty(AfterDelete))
                {
                    sql += ";" + AfterDelete;
                }
                // systemLog2.SaveLog(SystemLog.SystemLogType.SQL删除, sql);
            }
            OrderBy = orderBy;
            GetOperationType = operationType;
        }
        public OperationType GetOperationType
        {
            get; set;
        }
        public int PageSize
        {
            get; set;
        }
        public int PageIndex
        {
            get; set;
        }
        private string sql;
        /// <summary>
        /// 当前的SQL语句
        /// </summary>
        public string SQL
        {
            get
            {
                return sql;
            }
            set
            {
                sql = value;
            }
        }
        public string SQLOfSelect
        {
            get; set;
        }
        public string SQLOfCount
        {
            get; set;
        }
        public SqlParameter[] SqlParameters
        {
            get; set;
        }
        /// <summary>
        /// 键值对
        /// </summary>
        private NameValueCollection NameValueCollection
        {
            get; set;
        }

        private Dictionary<string, string> customerNameValue = new Dictionary<string, string>();
        /// <summary>
        /// 自行更新的字段值
        /// </summary>
        public Dictionary<string, string> CustomerNameValue
        {
            get
            {
                return customerNameValue;
            }
        }
        /// <summary>
        /// 客户端JSON对象
        /// </summary>
        private JToken JsToken
        {
            get; set;
        }
        public enum OperationType
        {
            Update = 0, Select = 1, Insert = 2, Delete = 3
        }
        public enum QueryMethod
        {
            模糊匹配 = 0, 精确匹配 = 1, 左匹配 = 2, 右匹配 = 3, 大于 = 4, 小于 = 5, 大于等于 = 6, 小于等于 = 7, 范围 = 8, 包含逗号 = 9, Null = 10, 大于0 = 11,IN=12, NOTIN =13,多个值与=14
        }
        public DataSet Ds
        { get; set; }
        /// <summary>
        /// 字典
        /// </summary>
        private DataTable DtDictionary
        {
            get; set;
        }
        bool IsQueryVisible = false;
        /// <summary>
        /// 获取数据集合，表1：数据，表2：页面及记录信息，表3：统计信息
        /// </summary>
        /// <returns></returns>
        public DataSet GetDs(bool isQueryVisible=false)
        {
            IsQueryVisible = isQueryVisible;
            GetSql(OperationType.Select);

            Ds = SqlHelper.ExecuteDataset(SqlHelper.MSSQLConnectionString, CommandType.Text, sql, SqlParameters);



            RecoredCount = long.Parse(Ds.Tables[1].Rows[0][0].ToString());
            PageCount = Math.Ceiling(decimal.Parse(RecoredCount.ToString()) / (PageSize <= 0 ? 1M : PageSize));
            Dt = Ds.Tables[0];
            return Ds;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public JsonResult ToJson()
        {

            if (Ds == null)
            {

                GetDs();


                Dt = Ds.Tables[0];

            }

            return ToJson(Ds, RecoredCount);
        }
        public void GetSql()
        {
            GetSql(OperationType.Select);

        }
        /// <summary>
        /// 返回树形JSON字符
        /// </summary>
        /// <param name="id">主键字段名</param>
        /// <param name="parentID">上级字段名</param>
        /// <returns></returns>
        public JsonResult ToJsonForString(string id, string parentID)
        {

            //GetSql(OperationType.Select);
            GetDs();

            RecoredCount = long.Parse(Ds.Tables[1].Rows[0][0].ToString());

            return ToJson(Ds, RecoredCount, parentID);

        }
        /// <summary>
        /// 记录数
        /// </summary>
        public long RecoredCount
        {
            get; set;
        }
        /// <summary>
        /// 页码数
        /// </summary>
        public decimal PageCount
        {
            get; set;
        }
        /// <summary>
        /// 数据表
        /// </summary>
        public DataTable Dt
        {
            get; set;
        }
        /// <summary>
        /// 返回JSON对象
        /// </summary>
        /// <param name="dt"></param>
        /// <param name="recordCount"></param>
        /// <returns></returns>
        public JsonResult ToJson(DataSet ds, long recordCount, string parentID = "")
        {

            JsonResult json = new JsonResult();
            DataTable dt = ds.Tables[0];

            object[] rows = new object[dt.Rows.Count];
            object[] foots = new object[listFoot.Count];
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                Dictionary<string, object> dicColumn = new Dictionary<string, object>();

                foreach (DataColumn dc in dt.Columns)
                {
                    string name = dc.ColumnName;
                    object value = dt.Rows[i][name];

                    if (dc.DataType == typeof(DateTime))
                    {

                        if (!string.IsNullOrEmpty(value.ToString()))
                        {
                            value = string.Format("{0:MM/dd/yyyy HH:mm:ss}", value);
                        }
                        else
                        {
                            value = "";
                        }


                    }
                    else if (dc.DataType == typeof(decimal))
                    {
                        value = string.Format("{0:G0}", value);
                    }

                    dicColumn.Add(name, value.ToString());
                    //选中
                    if (name == "UIIsCheck")
                    {
                        dicColumn.Add("checked", value.ToString().ToLower() == "true" ? "true" : "");

                    }


                }
                if (dt.Columns.Contains(parentID))
                {


                    string pid = dt.Rows[i][parentID].ToString();
                    //if(dt.Columns[parentID].DataType==typeof(int)|| dt.Columns[parentID].DataType == typeof(long))
                    //{
                    //    if(string.IsNullOrEmpty(pid))
                    //    {
                    //        pid = "0";
                    //    }
                    //}
                    if (!string.IsNullOrEmpty(parentID) && pid != "")
                    {
                        dicColumn.Add("_parentId", pid);
                    }
                }
                rows[i] = dicColumn;
            }
            if (ds.Tables.Count >= 3)
            {
                DataTable dataTable = ds.Tables[2];
                int footIndex = 0;
                foreach (string s in listFoot)
                {
                    Dictionary<string, object> dicColumn = new Dictionary<string, object>();
                    bool isShowFoot = false;
                    for (int i = 0; i < dataTable.Rows.Count; i++)
                    {



                        foreach (DataColumn dcParent in dt.Columns)
                        {
                            bool isFindColumn = false;
                            foreach (DataColumn dc in dataTable.Columns)
                            {

                                string name = dc.ColumnName;
                                if (name == s + dcParent.ColumnName)
                                {
                                    isFindColumn = true;

                                    object value = dataTable.Rows[i][name];
                                    dicColumn.Add(dcParent.ColumnName, value.ToString());
                                }

                            }
                            if (!isFindColumn)
                            {
                                string value = "";
                                if (!isShowFoot)
                                {
                                    isShowFoot = true;
                                    value = s + "：";
                                }
                                dicColumn.Add(dcParent.ColumnName, value);
                            }

                            //选中
                        }

                    }
                    foots[footIndex] = dicColumn;
                    footIndex++;
                }
            }
            json.Data = new { total = recordCount, rows = rows, footer = foots };
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            json.MaxJsonLength = int.MaxValue;
            return json;
        }
        /// <summary>
        /// 返回层级JSON对象
        /// </summary>
        /// <param name="dt"></param>
        /// <param name="recordCount"></param>
        /// <param name="parentID"></param>
        /// <returns></returns>
        public string ToJson(DataTable dt, int recordCount, string id, string parentID)
        {

            return @"{""total"":" + recordCount + @",""rows"":" + AddNode(dt, recordCount, id, parentID, "", 1) + "}";
        }
        /// <summary>  
        /// 无限递归，生成easyui tree可用的json数据 wyw308  
        /// </summary>  
        /// <param name="ParentID">父id</param>  
        /// <param name="deep">开始深度，默认为1</param>  
        /// <returns></returns>  
        private static string AddNode(DataTable dt, int recordCount, string id, string parentID, string parentIDValue, int deep)
        {
            string str = "";


            DataView dvTree = new DataView(dt);
            if (dt.Columns[parentID].DataType == typeof(string))
            {
                dvTree.RowFilter = "IsNull(" + parentID + ",'')='" + parentIDValue + "'";//过滤出ParentId  
            }
            else
            {
                if (string.IsNullOrEmpty(parentIDValue))
                {
                    parentIDValue = "0";
                }
                dvTree.RowFilter = "IsNull(" + parentID + ",'0')='" + parentIDValue + "'";//过滤出ParentId  
            }


            int i = 0;
            int d = deep;
            foreach (DataRowView drv in dvTree)
            {

                if (i == 0)//如果是某一层的开始，需要“[”开始  
                {
                    if (d == 1)//如果深度为1,即第一层  
                        str = "[";
                    else//否则，为第二层或更深  
                        str = ",\"children\":[";
                }

                else
                    str = str + ",";



                str = str + "{";
                foreach (DataColumn dc in dt.Columns)
                {
                    object value = drv[dc.ColumnName];
                    if (dc.DataType == typeof(DateTime))
                    {

                        if (!string.IsNullOrEmpty(value.ToString()))
                        {
                            value = string.Format("{0:MM/dd/yyyy HH:mm:ss}", value);
                        }
                        else
                        {
                            value = "";
                        }


                    }
                    str = str + "\"" + dc.ColumnName + "\":\"" + value.ToString().Replace("'", "\'").Replace("\"", "\\\"") + "\",";
                }
                str = str.TrimEnd(',');


                str = str + AddNode(dt, recordCount, id, parentID, drv[id].ToString(), deep + 1);//递归  

                str = str + "}";
                i = i + 1;

                if (dvTree.Count == i)//如果某一层到了末尾,需要"]"结束  
                    str = str + "]";

            }

            return str;
        }
        public static DataTable GetFieldByTableName(string tableName)
        {

            SqlParameter[] sqlParameters = new SqlParameter[1];
            sqlParameters[0] = new SqlParameter("@TableName", tableName);

            DataSet ds = SqlHelper.ExecuteDataset(SqlHelper.MSSQLConnectionString, "P_GetFieldByTableName", sqlParameters);
            return ds.Tables[0];


        }

        /// <summary>
        /// 导出
        /// </summary>
        /// <returns></returns>
        public string Export(bool isRedirect=true)
        {
            int columnIndex = 0;
            if (DictionaryID == 142)
            {//自动化报表加合计
                this.GetSql();
                columnIndex = 0;
                Dt = SqlHelper.ExecuteDataset(SqlHelper.MSSQLConnectionString, CommandType.Text, @"SELECT 
[机台],序号

      ,[工单单号]
      ,[品名]
      ,[产品规格]
      ,[工单数量]
      ,[ProcessName]
      ,[产品点数]
      ,[白班计划]
      ,[白班产量]
      ,[晚班计划]
      ,[晚班产量]
      ,[累计产量]
      ,cast([余量] as varchar(20)) as [余量]
      ,[计划产量]
      ,[实际产量]
      ,[计划点数]
      ,[实际点数]
      ,[产量达成率]
      ,[点数达成率]
      ,[原因]
      ,[DeptName]
      ,[WorkingDay]
      ,[OrganizeIDs] 
FROM 
(
SELECT  
[机台]
,CAST(ROW_NUMBER() OVER(PARTITION BY ProcessName,机台 ORDER BY ProcessName,机台) AS VARCHAR(10))   AS '序号'

      ,[工单单号]
      ,[品名]
      ,[产品规格]
      ,[工单数量]
      ,[ProcessName]
      ,[产品点数]
      ,[白班计划]
      ,[白班产量]
      ,[晚班计划]
      ,[晚班产量]
      ,[累计产量]
      ,cast([余量] as varchar(20)) as [余量]
      ,[计划产量]
      ,[实际产量]
      ,[计划点数]
      ,[实际点数]
      ,[产量达成率]
      ,[点数达成率]
      ,[原因]
      ,[DeptName]
      ,[WorkingDay]
      ,[OrganizeIDs]
,0    AS '序号2'
,0 AS '机台排序'

 FROM V_APS_SchedulingOutByMachine(nolock) WHERE 1=1   " + ResultWhere + @"
 

union all 
SELECT   
                                机台 as '机台'
   ,'合计'  AS '序号'

                                ,NULL as '工单单号'
                                ,NULL as '品名'
                                ,NULL as '产品规格'
                                ,NULL AS '工单数量'
                                ,ProcessName
                                ,NULL as '产品点数'
                                ,NULL AS '白班计划'
                                ,NULL AS '白班产量'
                                ,NULL AS '晚班计划'
                                ,NULL AS '晚班产量'
                                ,NULL as '累计产量'
                                ,NULL as '余量'
                                ,sum(计划产量) as '计划产量'
                                ,sum(实际产量) as '实际产量'
                                ,sum(计划点数) as '计划点数'
                                ,sum(实际点数) as '实际点数'
                                ,cast(cast(sum(实际产量)/(sum(计划产量)+0.0)*100 as decimal(9,2)) as varchar(10))+'%' as '产量达成率'
                                ,cast(cast(sum(实际点数)/(sum(计划点数)+0.0)*100 as decimal(9,2)) as varchar(10))+'%' as '点数达成率'
                                ,'' as '原因'
                                ,null as DeptName
                                ,NULL AS WorkingDay
                                ,NULL AS OrganizeIDs
                              ,1    AS '序号2'
,1 AS '机台排序'
                       
                                  FROM  V_APS_SchedulingOutByMachine(nolock)
                                  WHERE 1=1 " + ResultWhere + @"
                                  group by 机台,ProcessName



UNION ALL
SELECT   
                                NULL as '机台'
   ,'合计'  AS '序号'

                                ,NULL as '工单单号'
                                ,NULL as '品名'
                                ,NULL as '产品规格'
                                ,NULL AS '工单数量'
                                ,ProcessName
                                ,NULL as '产品点数'
                                ,NULL AS '白班计划'
                                ,NULL AS '白班产量'
                                ,NULL AS '晚班计划'
                                ,NULL AS '晚班产量'
                                ,NULL as '累计产量'
                                ,NULL as '余量'
                                ,sum(计划产量) as '计划产量'
                                ,sum(实际产量) as '实际产量'
                                ,sum(计划点数) as '计划点数'
                                ,sum(实际点数) as '实际点数'
                                ,cast(cast(sum(实际产量)/(sum(计划产量)+0.0)*100 as decimal(9,2)) as varchar(10))+'%' as '产量达成率'
                                ,cast(cast(sum(实际点数)/(sum(计划点数)+0.0)*100 as decimal(9,2)) as varchar(10))+'%' as '点数达成率'
                                ,'' as '原因'
                                ,null as DeptName
                                ,NULL AS WorkingDay
                                ,NULL AS OrganizeIDs
                              ,2   AS '序号2'
,2 AS '机台排序'
                                  FROM  V_APS_SchedulingOutByMachine(nolock)
                                   WHERE 1=1 " + ResultWhere + @"
                                  group by ProcessName
UNION ALL
SELECT   
          NULL as '机台'
   ,NULL AS '序号'
                      
                                ,NULL as '工单单号'
                                ,NULL as '品名'
                                ,NULL as '产品规格'
                                ,NULL AS '工单数量'
                                ,NULL AS ProcessName
                                ,NULL as '产品点数'
                                ,NULL AS '白班计划'
                                ,NULL AS '白班产量'
                                ,NULL AS '晚班计划'
                                ,NULL AS '晚班产量'
                                ,NULL as '累计产量'
                                ,'合计' as '余量'
                              ,sum(计划产量) as '计划产量'
                                ,sum(实际产量) as '实际产量'
                                ,sum(计划点数) as '计划点数'
                                ,sum(实际点数) as '实际点数'
                                ,cast(cast(sum(实际产量)/(sum(计划产量)+0.0)*100 as decimal(9,2)) as varchar(10))+'%' as '产量达成率'
                                ,cast(cast(sum(实际点数)/(sum(计划点数)+0.0)*100 as decimal(9,2)) as varchar(10))+'%' as '点数达成率'
                                ,'' as '原因'
                                ,null as DeptName
                                ,NULL AS WorkingDay
                                ,NULL AS OrganizeIDs
                                     ,3   AS '序号2'
,3 AS '机台排序'
                                  FROM  V_APS_SchedulingOutByMachine(nolock)
                                  WHERE 1=1 " + ResultWhere + @"
                                 

                            
) X
 
ORDER BY ISNULL(ProcessName,'工序'),isnull(机台,'机台'),机台排序
                            ", SqlParameters).Tables[0];



            }
            else
            {
                this.ToJson();

                if (Dt.Columns.IndexOf("RowNumber") > -1)
                {
                    columnIndex = 1;
                    Dt.Columns["RowNumber"].Caption = "序号";
                }
            }
            DataTable dtTableInfo = SqlHelper.ExecuteDataTable("SELECT * FROM Dev_DictionaryField WHERE DictionaryID=" + DictionaryID + " ORDER BY IsVisible desc,[FieldIndex]");
            //记录下拉替换的值为显示
            List<string> listCombox = new List<string>();
            foreach (DataRow dr in dtTableInfo.Rows)
            {


                string fieldName = dr["ParameterName"].ToString();
                if (dr["IsVisible"].ToString().ToLower() == "false" && Dt.Columns.Contains(fieldName))
                {//隐藏，但要读数据
                 // if (listCombox.Contains(fieldName) == false)
                    {
                        Dt.Columns.Remove(fieldName);

                    }
                    continue;
                }
                if (dr["ControlType"].ToString().ToLower() == "combobox" && !string.IsNullOrEmpty(dr["DataSourceID"].ToString()))
                {//下拉的，需要替换成显示的

                    string dataSourceID = dr["DataSourceID"].ToString();
                    DataTable dataTable = SqlHelper.ExecuteDataTable("SELECT USQL,DataText,DataValue FROM  Dev_DataSource WHERE dataSourceID='" + dataSourceID + "'");
                    if (dataTable.Rows.Count == 1)
                    {
                        string dataText = dataTable.Rows[0]["DataText"].ToString();
                        string dataValue = dataTable.Rows[0]["DataValue"].ToString();

                        if (Dt.Columns.Contains(dataText))
                        {//列包含

                            columnIndex++;
                            Dt.Columns[fieldName].SetOrdinal(columnIndex);
                            Dt.Columns[fieldName].Caption = dr["Comment"].ToString();
                            continue;
                            Dt.Columns[dataText].Caption = dr["Comment"].ToString();
                            Dt.Columns[dataText].SetOrdinal(columnIndex);
                            listCombox.Add(dataText);
                          
                      
                        }
                        else
                        {
                            Dt.Columns.Add(dataText);
                            Dt.Columns[dataText].Caption = dr["Comment"].ToString();
                            Dt.Columns[dataText].SetOrdinal(columnIndex);
                            listCombox.Add(dataText);
                            columnIndex++;
                            // Dt.Columns.Remove(fieldName);

                            DataTable dataTable1 = SqlHelper.ExecuteDataTable(dataTable.Rows[0]["USQL"].ToString());
                            foreach (DataRow dataRow in Dt.Rows)
                            {
                                DataRow[] dataRows = null;
                                if (Dt.Columns[fieldName].DataType == typeof(int)|| Dt.Columns[fieldName].DataType == typeof(long))
                                {
                                    if (!string.IsNullOrEmpty(dataRow[fieldName].ToString()))
                                        dataRows = dataTable1.Select(dataValue + "=" + dataRow[fieldName]);
                                }
                                else
                                {
                                    if (!string.IsNullOrEmpty(dataRow[fieldName].ToString()))
                                        dataRows = dataTable1.Select(dataValue + "='" + dataRow[fieldName] + "'");
                                }
                                if (dataRows != null && dataRows.Length == 1)
                                {
                                    dataRow[dataText] = dataRows[0][dataText];
                                }

                            }
                            Dt.Columns.Remove(fieldName);
                            continue;
                        }

                    }
                }
              
                if (Dt.Columns.Contains(fieldName))
                {//列包含
                    columnIndex++;
                    Dt.Columns[fieldName].Caption = dr["Comment"].ToString();
                    Dt.Columns[fieldName].SetOrdinal(columnIndex);
               
                }

            }
            if (DictionaryID == 142)
            {//自动化报表加序号

                Dt.Columns["序号"].SetOrdinal(1);
            }
            string url = NPOIHelper.TableToExcel(Dt, string.Format("{1}{0:yyyyMMddHHmmss}.xlsx", DateTime.Now, ObjectText), DictionaryID == 142 ? "机台" : "");
            if(isRedirect)
            {
                LicenceRuntime.Http.HttpContext.Response.Redirect(url);
            }

            return url;

        }
        /// <summary>
        /// 判定字段类型是否应该存为dbnull
        /// </summary>
        /// <param name="parameterName">字段</param>
        /// <param name="dataType">类型</param>
        /// <returns></returns>
        public static bool IsDbNull(string parameterName, string dataType)
        {
            bool result = false;
            switch (dataType.ToLower())
            {
                case "int":
                case "decimal":
                case "datetime":
                case "bigint":
                case "bit":
                case "float":
                case "numeric":
                case "real":
                    result = true;
                    break;

            }
            return result;
        }
        public  string ReplaceSQL(string sql)
        {
            if (dev_Account != null)
            {

                sql = sql.Replace("{CenterID}", dev_Account.CenterID.ToString());
                sql = sql.Replace("{GroupID}", dev_Account.GroupID.ToString());
                sql = sql.Replace("{ControlID}", dev_Account.GroupID.ToString());
            }

            return sql;
        }
        /// <summary>
        /// 根据字符返回NULL或者字符
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static string GetStringOrNull(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return "NULL";
            }
            else
            {
                return "'" + value.Replace("'", "''") + "'";
            }
        }

        /// <summary>el-date-picker / datebox 范围查询：解析 ISO、JSON 数组或字符串化数组。</summary>
        private static string NormalizeDateRangeQueryValue(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return string.Empty;

            raw = raw.Trim();
            if (raw.StartsWith('['))
            {
                try
                {
                    if (JToken.Parse(raw) is JArray arr && arr.Count > 0)
                    {
                        return string.Join(",",
                            arr.Select(t => NormalizeSingleDateQueryValue(t.ToString()))
                                .Where(s => !string.IsNullOrEmpty(s)));
                    }
                }
                catch
                {
                    // fallback: comma split below
                }
            }

            return string.Join(",",
                raw.Split(',')
                    .Select(NormalizeSingleDateQueryValue)
                    .Where(s => !string.IsNullOrEmpty(s)));
        }

        private static string NormalizeSingleDateQueryValue(string? raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return string.Empty;

            var s = raw.Trim().Trim('"', '\'');
            s = s.Replace("\r", string.Empty).Replace("\n", string.Empty).Replace("\\", string.Empty);
            if (s.Contains('T', StringComparison.Ordinal))
                s = s.Replace("Z", string.Empty, StringComparison.OrdinalIgnoreCase).Replace("T", " ");

            var plus = s.IndexOf('+');
            if (plus > 10)
                s = s[..plus].Trim();

            if (DateTimeOffset.TryParse(s, CultureInfo.InvariantCulture, DateTimeStyles.AllowWhiteSpaces, out var dto))
                return dto.LocalDateTime.ToString("yyyy-MM-dd HH:mm:ss");
            if (DateTime.TryParse(s, out var dt))
                return dt.ToString("yyyy-MM-dd HH:mm:ss");

            return s;
        }

    }
}

