# 从 EasyManufacture.Web/Global.asax.cs 提取定时任务相关方法到 Net10 GlobalLegacyApplication
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$src = Join-Path $root 'EasyManufacture.Web\Global.asax.cs'
$dst = Join-Path $PSScriptRoot '..\src\EasyManufacture.Infrastructure\Scheduling\Legacy\GlobalLegacyApplication.cs'

if (-not (Test-Path $src)) { throw "找不到 $src" }

$lines = Get-Content $src -Encoding UTF8
# 提取从 YRFSCranProcessMaterial 到文件末尾类内方法（跳过 Application_Start 与 MVC 管道）
$start = ($lines | Select-String -Pattern '^\s+public void YRFSCranProcessMaterial\(' | Select-Object -First 1).LineNumber
if (-not $start) { throw '未找到 YRFSCranProcessMaterial' }
$end = $lines.Count - 1
while ($end -gt 0 -and $lines[$end - 1] -notmatch '^\s*\}\s*$') { $end-- }

$body = $lines[($start - 1)..($end - 2)] -join "`n"
$body = $body -replace 'namespace EasyManufacture\.Web', ''
$body = $body -replace 'EasyManufacture\.Core\.SystemInterface\.EAST', 'EasyManufacture.Infrastructure.SystemInterface.EAST'
$body = $body -replace 'EasyManufacture\.Core\.SystemInterface\.JG', 'EasyManufacture.Infrastructure.SystemInterface.JG'
$body = $body -replace 'EasyManufacture\.Core\.SystemInterface\.K3Cloud', 'EasyManufacture.Infrastructure.SystemInterface.K3Cloud'
$body = $body -replace 'EasyManufacture\.Core\.SystemInterface', 'EasyManufacture.Infrastructure.SystemInterface'
$body = $body -replace '\bCore\.SystemInterface', 'EasyManufacture.Infrastructure.SystemInterface'
$body = $body -replace 'EasyManufacture\.Core\.', 'EasyManufacture.Infrastructure.Legacy.'
$body = $body -replace '\bAliClound\.', 'AliCloudIoT.'
$body = $body -replace 'private void Timer_Elapsed', 'public void Timer_Elapsed'
$body = $body -replace 'private void Timer_SendPlanChange', 'public void Timer_SendPlanChange'
$body = $body -replace 'private void ISGO\(', 'public void ISGO('
$body = $body -replace 'private void ISGO1\(', 'public void ISGO1('
$body = $body -replace 'private void EKMOToStart', 'public void EKMOToStart'
$body = $body -replace 'private String ', 'private string '
$body = $body -replace 'this\.systemLog', '_systemLog'
$body = $body -replace 'this\.resetBodyContentName', 'ResetBodyContentName'
$body = $body -replace 'this\.addToBodyContent', 'AddToBodyContent'
$body = $body -replace 'this\.systemLog', '_systemLog'

$header = @"
// <auto-generated>由 scripts/Migrate-GlobalAsax.ps1 自 Global.asax.cs 生成</auto-generated>
using EasyManufacture.Infrastructure.Legacy;
using EasyManufacture.Infrastructure.SystemInterface.EAST;
using EasyManufacture.Infrastructure.SystemInterface.JG;
using EasyManufacture.Infrastructure.SystemInterface.K3Cloud;
using EasyManufacture.Infrastructure.SystemInterface.IoT;
using EasyManufacture.Licence;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Data;
using System.Net.Http;
using System.Text;

namespace EasyManufacture.Infrastructure.Scheduling.Legacy;

/// <summary>旧 Global.asax 定时任务与辅助方法（由 Migrate-GlobalAsax.ps1 生成）。</summary>
public sealed class GlobalLegacyApplication
{
    private readonly SystemLog _systemLog = new();

"@

$footer = @"
}
"@

$dir = Split-Path $dst -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
Set-Content -Path $dst -Value ($header + $body + "`n" + $footer) -Encoding UTF8
Write-Host "已生成 $dst"
