# 将旧 EasyManufacture.Core/MvcControl/APSCore.cs 转为 Net10 的 ApsCoreEngine.LegacyCore.cs
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$src = Join-Path $root 'EasyManufacture.Core\MvcControl\APSCore.cs'
$dst = Join-Path $PSScriptRoot '..\src\EasyManufacture.Infrastructure\Legacy\ApsCoreEngine.LegacyCore.cs'

if (-not (Test-Path $src)) { throw "找不到 $src" }

$text = Get-Content $src -Raw -Encoding UTF8
$text = $text -replace 'namespace EasyManufacture\.Core\.MvcControl', 'namespace EasyManufacture.Infrastructure.Legacy'
$text = $text -replace 'public class APSCore : BaseController', 'public partial class ApsCoreEngine'
$text = $text -replace ': BaseController', ''
$text = $text -replace 'using System\.Web\.Mvc;', ''
$text = $text -replace 'using System\.Web;', ''
$text = $text -replace 'using System\.Web\.UI;', ''
$text = $text -replace 'using System\.Web\.UI\.WebControls;', ''
$text = $text -replace 'using System\.Data\.Entity;', ''
$text = $text -replace 'using System\.Data\.Entity\.Core\.Objects;', ''
$text = $text -replace 'using EasyManufacture\.Core\.DataBase;', 'using EasyManufacture.Infrastructure.Legacy;'
$text = $text -replace 'using EasyManufacture\.Core\.SystemInterface\.EAST;', 'using EasyManufacture.Infrastructure.SystemInterface.EAST;'
$text = $text -replace 'using EasyManufacture\.Core\.SystemInterface\.JG;', 'using EasyManufacture.Infrastructure.SystemInterface.JG;'
$text = $text -replace 'using EasyManufacture\.Core\.SystemInterface\.K3Cloud;', 'using EasyManufacture.Infrastructure.SystemInterface.K3Cloud;'
$text = $text -replace 'using EasyManufacture\.Core\.SystemInterface\.SAP;', 'using EasyManufacture.Infrastructure.SystemInterface.SAP;'
$text = $text -replace 'using EasyManufacture\.Core\.SystemInterface;', 'using EasyManufacture.Infrastructure.SystemInterface;'
$text = $text -replace 'using EasyManufacture\.Core;', 'using EasyManufacture.Infrastructure.Legacy;'
$text = $text -replace 'using static EasyManufacture\.Core\.DataBase\.MSSQLCore', 'using static EasyManufacture.Infrastructure.Legacy.MSSQLCore'
$text = $text -replace 'using static EasyManufacture\.Core\.SystemInterface\.SAP\.InterfaceSAP', 'using static EasyManufacture.Infrastructure.SystemInterface.SAP.InterfaceSAP'
$text = $text -replace 'EasyManufacture\.Core\.SystemInterface', 'EasyManufacture.Infrastructure.SystemInterface'
$text = $text -replace '\bCore\.SystemInterface', 'EasyManufacture.Infrastructure.SystemInterface'
$text = $text -replace 'System\.Data\.SqlClient', 'Microsoft.Data.SqlClient'
$text = $text -replace '\bbase\.', ''
# 去掉 MVC 管道残留
$text = $text -replace '(?ms)\s*public ActionResult Index\(\)\s*\{[^}]*\}\s*', "`n"
$text = $text -replace '(?ms)\s*protected override void Initialize\(System\.Web\.Routing\.RequestContext requestContext\)\s*\{.*?\n\s*\}\s*', "`n"
# 授权接口由 ApsCoreEngine.Register.cs / RegisterController 提供，避免与 LegacyCore 重复
$text = $text -replace '(?ms)\s*public string GetRegister\(\)\s*\{.*?\n\s*\}\s*', "`n"
$text = $text -replace '(?ms)\s*public string SeRegister\([^\)]*\)\s*\{.*?\n\s*\}\s*', "`n"
# EF6 DbSet.SqlQuery / DbSet.Where → EasyManufactureEntities 兼容 API
$text = $text -replace 'Entities\.V_([A-Za-z0-9_]+)\.SqlQuery\(', 'Entities.SqlQueryRaw<V_$1>('
$text = $text -replace 'Entities\.V_([A-Za-z0-9_]+)\.Where\(', 'Entities.Query<V_$1>().Where('
$text = $text -replace 'Entities\.V_([A-Za-z0-9_]+)\.AsNoTracking\(\)\.ToList\(\)', 'Entities.Query<V_$1>().ToList()'
$text = $text -replace 'Entities\.V_([A-Za-z0-9_]+)\.AsNoTracking\(\)', 'Entities.Query<V_$1>()'
$text = $text -replace 'Entities\.V_([A-Za-z0-9_]+)\.ToList\(\)', 'Entities.Query<V_$1>().ToList()'
$text = $text -replace 'Entities\.APS_([A-Za-z0-9_]+)\.Where\(', 'Entities.Query<APS_$1>().Where('
$text = $text -replace 'Entities\.Dev_([A-Za-z0-9_]+)\.Where\(', 'Entities.Query<Dev_$1>().Where('
$text = $text -replace ', new object\[\d+\]\)', ')'
$text = $text -replace 'Entities\.APS_([A-Za-z0-9_]+)\.AsNoTracking\(\)\.ToList\(\)', 'Entities.Query<APS_$1>().ToList()'
$text = $text -replace 'Entities\.APS_([A-Za-z0-9_]+)\.AsNoTracking\(\)', 'Entities.Query<APS_$1>()'
$text = $text -replace 'Entities\.Query<([^>]+)>\(\)\.AsNoTracking\(\)', 'Entities.Query<$1>()'
$text = $text -replace '\.AsNoTracking\(\)\.ToList\(\)', '.ToList()'
$text = $text -replace '\.AsNoTracking\(\)', ''
$text = $text -replace 'new\s+EasyManufacture\.Core\.SystemLog\(\)', 'new Licence.SystemLog()'
$text = $text -replace 'EasyManufacture\.Core\.SystemLog\.SystemLogType', 'Licence.SystemLog.SystemLogType'

$header = @"
// <auto-generated>
// 由 scripts/Migrate-ApsCore.ps1 自 EasyManufacture.Core/MvcControl/APSCore.cs 生成。
// EnableLegacyApsCoreSource=true 时编译；修改请改源文件后重跑脚本，勿手改本文件。
// </auto-generated>
using EasyManufacture.Application.Abstractions;
using EasyManufacture.Core;
using EasyManufacture.Core.ConfigTable;
using EasyManufacture.Entitys;
using EasyManufacture.Infrastructure.Legacy;
using EasyManufacture.Infrastructure.SystemInterface.EAST;
using EasyManufacture.Infrastructure.SystemInterface.JG;
using EasyManufacture.Infrastructure.SystemInterface.K3Cloud;
using EasyManufacture.Infrastructure.SystemInterface.SAP;
using EasyManufacture.Licence;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Data;
using Microsoft.Data.SqlClient;
using QueryMethod = EasyManufacture.Infrastructure.Legacy.MssqlQueryMethods.QueryMethod;

"@
if ($text -notmatch 'namespace EasyManufacture\.Infrastructure\.Legacy') {
    $text = $header + $text
}
Set-Content -Path $dst -Value $text -Encoding UTF8
Write-Host "已生成 $dst ($((Get-Item $dst).Length) bytes)"
