# 将旧 EasyManufacture.Core/DataBase/MSSQLCore.cs 转为 Net10 全量 MSSQLCore（LEGACY_APS_CORE 时编译）
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$src = Join-Path $root 'EasyManufacture.Core\DataBase\MSSQLCore.cs'
$dst = Join-Path $PSScriptRoot '..\src\EasyManufacture.Infrastructure\Legacy\MSSQLCore.LegacyFull.cs'

if (-not (Test-Path $src)) { throw "找不到 $src" }

$text = Get-Content $src -Raw -Encoding UTF8
$text = $text -replace 'namespace EasyManufacture\.Core\.DataBase', 'namespace EasyManufacture.Infrastructure.Legacy'
$text = $text -replace 'using System\.Data\.SqlClient', 'using Microsoft.Data.SqlClient'
$text = $text -replace 'using System\.Web;', ''
$text = $text -replace 'using System\.Web\.Mvc;', ''
$text = $text -replace 'using Org\.BouncyCastle\.Asn1\.Oscp;', ''
$text = $text -replace 'System\.Web\.HttpContext\.Current', 'LicenceRuntime.Http.HttpContext'
$text = $text -replace '\bHttpContext\.Current', 'LicenceRuntime.Http.HttpContext'
$text = $text -replace 'new EasyManufactureEntities\(\)', 'LegacyDbFactory.CreateEntities()'
$text = $text -replace 'new EasyManufactureEntities\(\)\.V_Dev_Account', 'LegacyDbFactory.CreateEntities().Query<V_Dev_Account>()'
$text = $text -replace '\bSqlHelper\.', 'SqlHelper.'

$header = @"
// <auto-generated>由 scripts/Migrate-MSSQLCore.ps1 生成；EnableLegacyApsCoreSource=true 时编译。</auto-generated>
using EasyManufacture.Entitys;
using EasyManufacture.Licence;
using Newtonsoft.Json.Linq;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Specialized;
using System.Globalization;
using System.Text;
using QueryMethod = EasyManufacture.Infrastructure.Legacy.MssqlQueryMethods.QueryMethod;

"@

if ($text -notmatch 'namespace EasyManufacture\.Infrastructure\.Legacy') {
    $text = $header + $text
}

Set-Content -Path $dst -Value $text -Encoding UTF8
Write-Host "已生成 $dst ($((Get-Item $dst).Length) bytes)"
